import { writable } from 'svelte/store';

export type MediaLang = 'en' | 'fr' | 'de' | 'es' | 'vi' | 'ja' | 'ko';

export const currentLang = writable<MediaLang>('en');

export const translations: Record<MediaLang, {
  headerTitle: string;
  headerSub: string;
  headerBadge: string;
  metaTitle: string;
  metaDesc: string;
  title: string;
  desc: string;
  subNotice: string;
  tabCompress: string;
  tabResize: string;
  compressPresetTitle: string;
  compressPresetSub: string;
  presetStd: string;
  presetStdDesc: string;
  presetHigh: string;
  presetHighDesc: string;
  presetGov: string;
  presetGovDesc: string;
  presetResume: string;
  presetResumeDesc: string;
  resizePresetTitle: string;
  resizePresetSub: string;
  resizeResume: string;
  resizeResumeDesc: string;
  resizePassport: string;
  resizePassportDesc: string;
  resizeGov: string;
  resizeGovDesc: string;
  resizeSns: string;
  resizeSnsDesc: string;
  dropTitle: string;
  dropSub: string;
  saveFormat: string;
  formatJpg: string;
  formatWebp: string;
  formatPng: string;
  qualityLabel: string;
  processedTotalPrefix: string;
  processedTotalSuffix: string;
  downloadZip: string;
  clearAll: string;
  resolution: string;
  savedRate: string;
  downloadSingle: string;
  processing: string;
  delete: string;
  faqTitle: string;
  faq1Q: string;
  faq1A: string;
  faq2Q: string;
  faq2A: string;
  faq3Q: string;
  faq3A: string;
}> = {
  en: {
    headerTitle: 'Zero-Upload Media Tools',
    headerSub: 'ZeroUpload Media Tools',
    headerBadge: '🔒 100% Client-Side Processing (0KB Server Upload)',
    metaTitle: 'Zero-Upload Photo Resizer & Compressor - FastPic',
    metaDesc: 'Resize photos for passports, resumes (3x4cm) & government submissions directly in your browser. Zero bytes uploaded to remote servers. Bulk ZIP export.',
    title: 'Zero-Upload Photo Resizer & Compressor',
    desc: 'Confidential portrait or ID photos never leave your device. Processed 100% client-side inside your browser sandbox.',
    subNotice: '📄 Resume (3x4cm) • 🛂 Passport (3.5x4.5cm) • 🏛️ Official Document Compress & Resize',
    tabCompress: '🗜️ 1. Compress File Size',
    tabResize: '📐 2. Resize Dimensions',
    compressPresetTitle: '⚡ Quick Compression Presets',
    compressPresetSub: 'Preserve pixel resolution while trimming byte size',
    presetStd: '🎯 Standard Balanced',
    presetStdDesc: '80% Quality • JPG',
    presetHigh: '🚀 Maximum Compress',
    presetHighDesc: '60% Quality • WebP',
    presetGov: '🏛️ Official Submissions',
    presetGovDesc: 'Under 1MB target',
    presetResume: '📄 Job Portals',
    presetResumeDesc: '100KB~300KB target',
    resizePresetTitle: '⚡ ID Photo & Document Dimensions',
    resizePresetSub: 'Automatically fit required width × height dimensions',
    resizeResume: '📄 Job / Resume Photo',
    resizeResumeDesc: '3x4cm (354x472px)',
    resizePassport: '🛂 Passport / National ID',
    resizePassportDesc: '3.5x4.5cm (413x531px)',
    resizeGov: '🏛️ Doc Scan Scaler',
    resizeGovDesc: 'Max width 1600px',
    resizeSns: '📱 SNS Square',
    resizeSnsDesc: '1:1 (1080x1080px)',
    dropTitle: 'Drop portrait or document photos here, or click to browse',
    dropSub: 'No file size limits • Processed entirely in client memory',
    saveFormat: 'Target Format',
    formatJpg: 'JPG / JPEG (Portal standard)',
    formatWebp: 'WebP (Modern web recommended)',
    formatPng: 'PNG (Lossless sharpness)',
    qualityLabel: 'Quality / Compression Ratio',
    processedTotalPrefix: 'Total',
    processedTotalSuffix: 'photos ready',
    downloadZip: 'Download All (ZIP)',
    clearAll: 'Clear all',
    resolution: 'Resolution',
    savedRate: 'reduced',
    downloadSingle: 'Download',
    processing: 'Processing...',
    delete: 'Delete',
    faqTitle: 'Frequently Asked Questions (FAQ)',
    faq1Q: 'Q. What is the difference between Compress and Resize?',
    faq1A: 'Compression reduces file byte size (KB/MB) while keeping pixel dimensions unchanged. Resizing changes the actual canvas width and height to match official specifications such as resumes or passports.',
    faq2Q: 'Q. Can I process multiple photos and download as a ZIP file?',
    faq2A: 'Yes! Select multiple photos at once and download them individually or as a single combined ZIP archive.',
    faq3Q: 'Q. Is there any server file size upload quota?',
    faq3A: 'No. Since this tool runs 100% locally in your browser memory without transmitting bytes to any cloud server, you are not subject to server payload limits.'
  },
  fr: {
    headerTitle: 'Outils Média Zéro-Téléversement',
    headerSub: 'ZeroUpload Media Tools',
    headerBadge: '🔒 100% Côté Client (0KB Téléversé)',
    metaTitle: 'Redimensionner et Compresser Photos - FastPic (Zéro Serveur)',
    metaDesc: 'Redimensionnez vos photos d\'identité (passeport, CV 3x4cm) et compressez vos images directement dans votre navigateur.',
    title: 'Compresseur & Redimensionneur de Photos Sécurisé',
    desc: 'Vos photos d\'identité ou de documents privés ne quittent jamais votre appareil. Traitement 100% local en mémoire vive.',
    subNotice: '📄 Photo de CV (3x4cm) • 🛂 Passeport (3,5x4,5cm) • 🏛️ Démarches administratives',
    tabCompress: '🗜️ 1. Réduire le Poids (Compression)',
    tabResize: '📐 2. Changer les Dimensions (Redimensionnement)',
    compressPresetTitle: '⚡ Préréglages de Compression Rapide',
    compressPresetSub: 'Préservez la résolution tout en réduisant la taille du fichier',
    presetStd: '🎯 Standard Équilibré',
    presetStdDesc: 'Qualité 80% • JPG',
    presetHigh: '🚀 Compression Maximale',
    presetHighDesc: 'Qualité 60% • WebP',
    presetGov: '🏛️ Documents Officiels',
    presetGovDesc: 'Moins de 1 Mo',
    presetResume: '📄 Portails d\'Emploi',
    presetResumeDesc: '100 Ko ~ 300 Ko',
    resizePresetTitle: '⚡ Formats de Photos d\'Identité',
    resizePresetSub: 'Ajustement automatique aux dimensions largeur × hauteur exigées',
    resizeResume: '📄 Photo de CV',
    resizeResumeDesc: '3x4 cm (354x472 px)',
    resizePassport: '🛂 Passeport / CNI',
    resizePassportDesc: '3,5x4,5 cm (413x531 px)',
    resizeGov: '🏛️ Numérisation Document',
    resizeGovDesc: 'Largeur max 1600 px',
    resizeSns: '📱 Carré Réseaux Sociaux',
    resizeSnsDesc: '1:1 (1080x1080 px)',
    dropTitle: 'Glissez vos photos ici, ou cliquez pour parcourir',
    dropSub: 'Aucune limite de taille • Traité intégralement dans la mémoire de votre navigateur',
    saveFormat: 'Format de Sortie',
    formatJpg: 'JPG / JPEG (Standard universel)',
    formatWebp: 'WebP (Recommandé pour le web)',
    formatPng: 'PNG (Netteté sans perte)',
    qualityLabel: 'Qualité / Taux de Compression',
    processedTotalPrefix: 'Total de',
    processedTotalSuffix: 'photos prêtes',
    downloadZip: 'Télécharger Tout (ZIP)',
    clearAll: 'Tout effacer',
    resolution: 'Résolution',
    savedRate: 'économisé',
    downloadSingle: 'Télécharger',
    processing: 'Traitement...',
    delete: 'Supprimer',
    faqTitle: 'Foire Aux Questions (FAQ)',
    faq1Q: 'Q. Quelle est la différence entre Compresser et Redimensionner ?',
    faq1A: 'La compression réduit le poids en octets (Ko/Mo) sans changer le nombre de pixels. Le redimensionnement adapte les dimensions en pixels aux formats officiels (CV, passeport).',
    faq2Q: 'Q. Puis-je traiter plusieurs photos à la fois et les exporter en ZIP ?',
    faq2A: 'Oui ! Sélectionnez plusieurs photos à la fois et téléchargez-les individuellement ou regroupées en une seule archive ZIP.',
    faq3Q: 'Q. Existe-t-il une limite de taille imposée par le serveur ?',
    faq3A: 'Non. Cet outil s\'exécute 100% localement dans le navigateur sans envoyer de données à un serveur, contournant ainsi toutes les limites de téléversement.'
  },
  de: {
    headerTitle: 'Zero-Upload Foto- & Mediastudios',
    headerSub: 'ZeroUpload Media Tools',
    headerBadge: '🔒 100% Lokale Browser-Verarbeitung (0KB Upload)',
    metaTitle: 'Passfoto Resizer & Bildkompressor - FastPic (Ohne Server)',
    metaDesc: 'Fotos für Pass, Bewerbungsfoto (3x4cm) und Behörden direkt im Browser anpassen und komprimieren. Keine Speicherung.',
    title: 'Sicherer Foto-Kompressor & Passfoto-Resizer',
    desc: 'Bewerbungs- und Passfotos verlassen niemals Ihr Gerät. 100% lokale Bildverarbeitung im Browser-Speicher.',
    subNotice: '📄 Bewerbung (3x4cm) • 🛂 Passfoto (3,5x4,5cm) • 🏛️ Behördenvorgaben',
    tabCompress: '🗜️ 1. Dateigröße Verringern (Komprimierung)',
    tabResize: '📐 2. Passfoto-Maße Anpassen (Resize)',
    compressPresetTitle: '⚡ Schnelle Komprimierungs-Profile',
    compressPresetSub: 'Pixelauflösung beibehalten und Dateigröße stark verringern',
    presetStd: '🎯 Standard Ausgewogen',
    presetStdDesc: '80% Qualität • JPG',
    presetHigh: '🚀 Maximale Kompression',
    presetHighDesc: '60% Qualität • WebP',
    presetGov: '🏛️ Behördendokumente',
    presetGovDesc: 'Ziel unter 1MB',
    presetResume: '📄 Jobportale',
    presetResumeDesc: '100KB ~ 300KB Ziel',
    resizePresetTitle: '⚡ Passbild- & Dokumentenformate',
    resizePresetSub: 'Automatische Anpassung an geforderte Pixelmaße',
    resizeResume: '📄 Bewerbungsfoto',
    resizeResumeDesc: '3x4cm (354x472px)',
    resizePassport: '🛂 Reisepass / Personalausweis',
    resizePassportDesc: '3,5x4,5cm (413x531px)',
    resizeGov: '🏛️ Dokumentscan Skalierung',
    resizeGovDesc: 'Breite max 1600px',
    resizeSns: '📱 Social Media Quadrat',
    resizeSnsDesc: '1:1 (1080x1080px)',
    dropTitle: 'Fotos hierher ziehen oder zum Auswählen klicken',
    dropSub: 'Keine Größenbeschränkung • Vollständig im lokalen RAM verarbeitet',
    saveFormat: 'Zielformat',
    formatJpg: 'JPG / JPEG (Standard)',
    formatWebp: 'WebP (Modernes Webformat)',
    formatPng: 'PNG (Verlustfrei scharf)',
    qualityLabel: 'Qualität / Kompressionsrate',
    processedTotalPrefix: 'Insgesamt',
    processedTotalSuffix: 'Fotos verarbeitet',
    downloadZip: 'Alle Herunterladen (ZIP)',
    clearAll: 'Alle löschen',
    resolution: 'Auflösung',
    savedRate: 'eingespart',
    downloadSingle: 'Download',
    processing: 'Verarbeite...',
    delete: 'Löschen',
    faqTitle: 'Häufig gestellte Fragen (FAQ)',
    faq1Q: 'Q. Was ist der Unterschied zwischen Komprimieren und Resizen?',
    faq1A: 'Komprimieren verringert die Dateigröße in KB/MB ohne Veränderung der Pixelabmessungen. Resizen ändert die tatsächliche Bildgröße auf geforderte Maße (z.B. Passfoto 3,5x4,5cm).',
    faq2Q: 'Q. Kann ich mehrere Fotos verarbeiten und als ZIP herunterladen?',
    faq2A: 'Ja! Mehrere Bilder können auf einmal verarbeitet und einzeln oder als bequeme ZIP-Datei heruntergeladen werden.',
    faq3Q: 'Q. Gibt es eine Begrenzung der Dateigröße?',
    faq3A: 'Nein. Da die Verarbeitung direkt in Ihrem Browser stattfindet, gibt es keine serverseitigen Dateibeschränkungen.'
  },
  es: {
    headerTitle: 'Herramientas de Medios Cero Carga',
    headerSub: 'ZeroUpload Media Tools',
    headerBadge: '🔒 100% en Navegador (0KB Subida)',
    metaTitle: 'Compresor y Redimensionador de Fotos - FastPic',
    metaDesc: 'Redimensione fotos para pasaportes, currículum (3x4cm) y trámites oficiales directamente en su navegador.',
    title: 'Compresor y Redimensionador de Fotos Privado',
    desc: 'Fotos de identificación y documentos personales nunca salen de su dispositivo. Procesamiento 100% local en memoria.',
    subNotice: '📄 Currículum (3x4cm) • 🛂 Pasaporte (3.5x4.5cm) • 🏛️ Documentación Oficial',
    tabCompress: '🗜️ 1. Reducir Tamaño de Archivo (Comprimir)',
    tabResize: '📐 2. Ajustar Medidas de Foto (Redimensionar)',
    compressPresetTitle: '⚡ Ajustes Rápidos de Compresión',
    compressPresetSub: 'Conserve la resolución reduciendo los bytes',
    presetStd: '🎯 Estándar Equilibrado',
    presetStdDesc: 'Calidad 80% • JPG',
    presetHigh: '🚀 Compresión Máxima',
    presetHighDesc: 'Calidad 60% • WebP',
    presetGov: '🏛️ Trámites Oficiales',
    presetGovDesc: 'Menor a 1MB',
    presetResume: '📄 Portales de Empleo',
    presetResumeDesc: '100KB ~ 300KB',
    resizePresetTitle: '⚡ Formatos de Fotos de Identificación',
    resizePresetSub: 'Ajuste automático a medidas de ancho × alto requeridas',
    resizeResume: '📄 Foto de Currículum',
    resizeResumeDesc: '3x4cm (354x472px)',
    resizePassport: '🛂 Pasaporte / DNI',
    resizePassportDesc: '3.5x4.5cm (413x531px)',
    resizeGov: '🏛️ Escaneo de Documento',
    resizeGovDesc: 'Ancho máx 1600px',
    resizeSns: '📱 Cuadrado Redes Sociales',
    resizeSnsDesc: '1:1 (1080x1080px)',
    dropTitle: 'Arrastre fotos aquí o haga clic para buscar',
    dropSub: 'Sin límite de tamaño • Procesado totalmente en memoria local',
    saveFormat: 'Formato de Guardado',
    formatJpg: 'JPG / JPEG (Estándar)',
    formatWebp: 'WebP (Recomendado para web)',
    formatPng: 'PNG (Nitidez sin pérdidas)',
    qualityLabel: 'Calidad / Ratio de Compresión',
    processedTotalPrefix: 'Total de',
    processedTotalSuffix: 'fotos listas',
    downloadZip: 'Descargar Todo (ZIP)',
    clearAll: 'Borrar todo',
    resolution: 'Resolución',
    savedRate: 'reducido',
    downloadSingle: 'Descargar',
    processing: 'Procesando...',
    delete: 'Eliminar',
    faqTitle: 'Preguntas Frecuentes (FAQ)',
    faq1Q: 'Q. ¿Cuál es la diferencia entre Comprimir y Redimensionar?',
    faq1A: 'Comprimir reduce el tamaño del archivo en KB/MB manteniendo la resolución de píxeles. Redimensionar ajusta las dimensiones de la imagen al formato oficial requerido (CV, pasaporte).',
    faq2Q: 'Q. ¿Puedo procesar varias imágenes y descargarlas en ZIP?',
    faq2A: '¡Sí! Puede seleccionar varias fotos y descargarlas por separado o todas en un único archivo ZIP comprimido.',
    faq3Q: 'Q. ¿Existe algún límite de subida?',
    faq3A: 'No. Dado que se procesa 100% en el navegador, no hay límites de transferencia en servidor.'
  },
  vi: {
    headerTitle: 'Công Cụ Ảnh & Media Cục Bộ',
    headerSub: 'ZeroUpload Media Tools',
    headerBadge: '🔒 100% Xử Lý Trực Tiếp Trên Trình Duyệt (0KB Upload)',
    metaTitle: 'Nén Ảnh & Đổi Kích Thước Ảnh Thẻ Chuẩn - FastPic',
    metaDesc: 'Nén dung lượng ảnh và đổi kích thước ảnh thẻ 3x4cm, hộ chiếu 3.5x4.5cm trực tiếp trên trình duyệt. Không tải dữ liệu lên server.',
    title: 'Nén Dung Lượng & Đổi Kích Thước Ảnh Thẻ',
    desc: 'Ảnh thẻ cá nhân và tài liệu mật không bao giờ rời khỏi thiết bị của bạn. Xử lý an toàn 100% trong bộ nhớ máy.',
    subNotice: '📄 Ảnh CV (3x4cm) • 🛂 Hộ chiếu/CCCD (3.5x4.5cm) • 🏛️ Nén hồ sơ nộp trực tuyến',
    tabCompress: '🗜️ 1. Giảm Dung Lượng File (Nén)',
    tabResize: '📐 2. Chỉnh Kích Thước Ảnh Thẻ (Resize)',
    compressPresetTitle: '⚡ Cấu Hình Nén Nhanh',
    compressPresetSub: 'Giữ nguyên độ sắc nét trong khi tối ưu dung lượng KB/MB',
    presetStd: '🎯 Nén Chuẩn Tiêu Chuẩn',
    presetStdDesc: 'Chất lượng 80% • JPG',
    presetHigh: '🚀 Nén Siêu Nhẹ',
    presetHighDesc: 'Chất lượng 60% • WebP',
    presetGov: '🏛️ Nộp Hồ Sơ Trực Tuyến',
    presetGovDesc: 'Dưới 1MB an toàn',
    presetResume: '📄 Website Tuyển Dụng',
    presetResumeDesc: 'Khoảng 100KB ~ 300KB',
    resizePresetTitle: '⚡ Kích Thước Ảnh Thẻ Thông Dụng',
    resizePresetSub: 'Tự động cắt ghép chuẩn chiều rộng × chiều cao theo quy định',
    resizeResume: '📄 Ảnh Thẻ 3x4 (CV/Hồ sơ)',
    resizeResumeDesc: '3x4cm (354x472px)',
    resizePassport: '🛂 Ảnh Hộ Chiếu / Visa',
    resizePassportDesc: '3.5x4.5cm (413x531px)',
    resizeGov: '🏛️ Thu Nhỏ Văn Bản',
    resizeGovDesc: 'Chiều rộng tối đa 1600px',
    resizeSns: '📱 Vuông Mạng Xã Hội',
    resizeSnsDesc: '1:1 (1080x1080px)',
    dropTitle: 'Kéo thả ảnh vào đây hoặc nhấn để chọn file (nhiều ảnh cùng lúc)',
    dropSub: 'Không giới hạn dung lượng • Xử lý tức thì trong RAM thiết bị',
    saveFormat: 'Định Dạng Lưu',
    formatJpg: 'JPG / JPEG (Phổ biến nhất)',
    formatWebp: 'WebP (Định dạng web tối ưu)',
    formatPng: 'PNG (Không giảm chất lượng)',
    qualityLabel: 'Chất Lượng / Tỷ Lệ Nén',
    processedTotalPrefix: 'Đã xử lý xong',
    processedTotalSuffix: 'ảnh',
    downloadZip: 'Tải Về File ZIP Trọn Bộ',
    clearAll: 'Xóa tất cả',
    resolution: 'Độ phân giải',
    savedRate: 'giảm',
    downloadSingle: 'Tải về',
    processing: 'Đang xử lý...',
    delete: 'Xóa',
    faqTitle: 'Câu Hỏi Thường Gặp (FAQ)',
    faq1Q: 'Q. Nén ảnh và Đổi kích thước khác nhau thế nào?',
    faq1A: 'Nén ảnh giữ nguyên số lượng pixel nhưng giảm dung lượng file (KB/MB) để dễ gửi qua mạng. Đổi kích thước thay đổi tỷ lệ pixel của ảnh để khớp với các quy định ảnh thẻ (như 3x4cm hay hộ chiếu).',
    faq2Q: 'Q. Tôi có thể xử lý nhiều ảnh cùng lúc và tải file ZIP không?',
    faq2A: 'Có! Bạn có thể chọn hàng loạt ảnh và nhấn nút [📦 Tải Về File ZIP Trọn Bộ] để nhận toàn bộ ảnh đã xử lý.',
    faq3Q: 'Q. Ảnh của tôi có bị tải lên máy chủ ngoài không?',
    faq3A: 'Không. Toàn bộ quá trình xử lý diễn ra ngay trên CPU máy tính/điện thoại của bạn, bảo mật tuyệt đối 100%.'
  },
  ja: {
    headerTitle: 'サーバー無送信・写真＆画像編集ツール',
    headerSub: 'ZeroUpload Media Tools',
    headerBadge: '🔒 100% ブラウザ内ローカル処理 (サーバー送信0KB)',
    metaTitle: '安心・写真圧縮＆証明写真サイズリサイズ - FastPic',
    metaDesc: 'サーバー送信0KBでプライバシー保護。履歴書用3x4cm、パスポート用3.5x4.5cm写真の規格リサイズと画像容量圧縮。ZIP一括ダウンロード対応。',
    title: '安心・写真容量圧縮＆証明写真サイズ変換',
    desc: '顔写真や重要書類が外部サーバーに送信・保存される心配なく、お使いの端末内で100%安全に処理します。',
    subNotice: '📄 履歴書写真(3x4cm) • 🛂 パスポート写真(3.5x4.5cm) • 🏛️ 公的申請用サイズ調整',
    tabCompress: '🗜️ 1. ファイル容量圧縮 (KB/MB削減)',
    tabResize: '📐 2. 写真規格サイズ変換 (リサイズ)',
    compressPresetTitle: '⚡ クイック容量圧縮プリセット',
    compressPresetSub: '解像度をできる限り維持しながらファイルサイズのみを軽量化',
    presetStd: '🎯 標準バランス圧縮',
    presetStdDesc: '品質80% • JPG',
    presetHigh: '🚀 超高効率圧縮',
    presetHighDesc: '品質60% • WebP',
    presetGov: '🏛️ 公的申請書類向け',
    presetGovDesc: '1MB以下ターゲット',
    presetResume: '📄 就職・転職ポータル',
    presetResumeDesc: '100KB〜300KBターゲット',
    resizePresetTitle: '⚡ 証明写真・提出規格プリセット',
    resizePresetSub: '提出先が指定する幅×高さピクセル比率に自動調整',
    resizeResume: '📄 履歴書用写真',
    resizeResumeDesc: '3x4cm (354x472px)',
    resizePassport: '🛂 パスポート・マイナンバー',
    resizePassportDesc: '3.5x4.5cm (413x531px)',
    resizeGov: '🏛️ 書類スキャン縮小',
    resizeGovDesc: '横幅最大1600px',
    resizeSns: '📱 SNS用正方形',
    resizeSnsDesc: '1:1 (1080x1080px)',
    dropTitle: '証明写真や書類画像をドラッグ＆ドロップ、または選択 (複数枚対応)',
    dropSub: 'ファイルサイズ上限なし • ブラウザメモリ内で高速・安全に処理',
    saveFormat: '保存フォーマット',
    formatJpg: 'JPG / JPEG (標準規格)',
    formatWebp: 'WebP (高効率Web推奨)',
    formatPng: 'PNG (可逆圧縮・鮮明)',
    qualityLabel: '画質 / 圧縮率',
    processedTotalPrefix: '合計',
    processedTotalSuffix: '枚の写真処理完了',
    downloadZip: 'ZIP一括ダウンロード',
    clearAll: 'すべて削除',
    resolution: '解像度',
    savedRate: '削減',
    downloadSingle: 'ダウンロード',
    processing: '処理中...',
    delete: '削除',
    faqTitle: 'よくある質問 (FAQ)',
    faq1Q: 'Q. 容量圧縮と規格リサイズの違いは何ですか？',
    faq1A: '容量圧縮はピクセル寸法を維持したままファイルサイズ(KB/MB)のみを削減します。規格リサイズは履歴書(3x4cm)やパスポート(3.5x4.5cm)など指定された比率に写真そのものを変更します。',
    faq2Q: 'Q. 複数枚の写真を一括処理してZIPで保存できますか？',
    faq2A: 'はい！複数枚をまとめて選択し、個別ダウンロードまたは[ZIP一括ダウンロード]ボタンでまとめて保存可能です。',
    faq3Q: 'Q. 写真が外部サーバーにアップロードされることはありますか？',
    faq3A: '一切ありません。すべての処理はお使いの端末のブラウザ内だけで完結するため、情報漏洩の心配なくご利用いただけます。'
  },
  ko: {
    headerTitle: '제로업로드 미디어 툴',
    headerSub: 'ZeroUpload Media Tools',
    headerBadge: '🔒 100% 브라우저 로컬 처리 (서버 전송 0KB)',
    metaTitle: '제로업로드 안심 사진 압축 & 규격 리사이즈 도구',
    metaDesc: '서버 전송 0KB, 개인정보 100% 보호. 취업 이력서 3x4cm, 여권 3.5x4.5cm 사진 규격 리사이즈 및 이미지 용량(KB/MB) 압축. ZIP 일괄 다운로드 지원.',
    title: '안심 사진 압축 & 규격 리사이즈',
    desc: '주민번호나 얼굴 사진이 외부 서버에 저장될 걱정 없이, 내 브라우저(PC/스마트폰)에서 100% 안전하게 즉시 변환합니다.',
    subNotice: '📄 이력서(3x4cm) • 🛂 여권(3.5x4.5cm) • 🏛️ 정부24/공공기관 첨부서류 용량 맞춤 등 원클릭 지원',
    tabCompress: '🗜️ 1. 파일 용량 줄이기 (압축)',
    tabResize: '📐 2. 사진 규격 맞추기 (리사이즈)',
    compressPresetTitle: '⚡ 용량 압축 빠른 프리셋',
    compressPresetSub: '사진 크기(해상도)는 최대한 보존하며 바이트만 절감',
    presetStd: '🎯 일반 표준 압축',
    presetStdDesc: '품질 80% • JPG',
    presetHigh: '🚀 초고효율 압축',
    presetHighDesc: '품질 60% • WebP',
    presetGov: '🏛️ 정부24 서류용',
    presetGovDesc: '1MB 이하 안전 압축',
    presetResume: '📄 취업사이트 서류',
    presetResumeDesc: '100KB~300KB 타겟',
    resizePresetTitle: '⚡ 증명사진 & 제출 규격 프리셋',
    resizePresetSub: '제출처 요구 가로 x 세로 픽셀 치수에 자동 맞춤',
    resizeResume: '📄 취업/이력서 사진',
    resizeResumeDesc: '3x4cm (354x472px)',
    resizePassport: '🛂 여권/주민등록증',
    resizePassportDesc: '3.5x4.5cm (413x531px)',
    resizeGov: '🏛️ 서류 원본축소',
    resizeGovDesc: '가로 최대 1600px',
    resizeSns: '📱 SNS 정방형',
    resizeSnsDesc: '1:1 (1080x1080px)',
    dropTitle: '증명사진이나 서류 이미지를 드래그하거나 클릭하세요 (여러 장 동시 가능)',
    dropSub: '서버 업로드 용량 제한 없음 • 내 PC 메모리에서 100% 안전하게 즉시 연산',
    saveFormat: '저장 포맷',
    formatJpg: 'JPG / JPEG (공공기관 및 취업포털 표준)',
    formatWebp: 'WebP (초고압축 웹 표준 권장)',
    formatPng: 'PNG (무손실 선명도 유지)',
    qualityLabel: '화질 / 압축율',
    processedTotalPrefix: '총',
    processedTotalSuffix: '개의 사진 처리 완료',
    downloadZip: '전체 ZIP 파일 다운로드',
    clearAll: '모두 비우기',
    resolution: '해상도',
    savedRate: '절감',
    downloadSingle: '다운로드',
    processing: '처리 중...',
    delete: '삭제',
    faqTitle: '자주 묻는 질문 (FAQ)',
    faq1Q: 'Q. 용량 압축(Compress)과 규격 리사이즈(Resize)는 어떻게 다른가요?',
    faq1A: '용량 압축은 사진 크기(픽셀 치수)를 유지한 채 파일 바이트(KB/MB)만 줄여 500KB나 1MB 등 제출 제한에 맞출 때 사용합니다. 반면 규격 리사이즈는 취업 이력서(3x4cm)나 여권(3.5x4.5cm) 등 정해진 규격 픽셀 비율로 사진 크기 자체를 변환할 때 사용합니다.',
    faq2Q: 'Q. 여러 장의 사진을 한 번에 줄이고 ZIP 파일로 받을 수 있나요?',
    faq2A: '네! 여러 장의 이미지를 동시에 선택하거나 드래그하여 올리면 각각 개별 다운로드하거나, [📦 전체 ZIP 파일 다운로드] 버튼을 통해 한 번의 압축 파일로 묶어서 다운로드하실 수 있습니다.',
    faq3Q: 'Q. Vercel이나 서버의 업로드 용량 제한에 걸리지 않나요?',
    faq3A: '이 웹사이트는 정적(Static SPA) 방식으로 배포되어 있어 서버로 파일을 전송하지 않습니다. 모든 작업은 고객님의 컴퓨터나 스마트폰 웹브라우저 메모리 안에서만 실행되므로, 일반 클라우드 서버의 4.5MB 업로드 제한을 전혀 받지 않습니다.'
  }
};
