import { writable } from 'svelte/store';

export type MediaLang = 'ko' | 'en';

export const currentLang = writable<MediaLang>('en');

export const translations = {
  ko: {
    headerTitle: '제로업로드 미디어 툴',
    headerSub: 'ZeroUpload Media Tools',
    headerBadge: '🔒 100% 브라우저 로컬 처리 (서버 전송 0KB)',
    metaTitle: '제로업로드 안심 사진 압축 & 규격 리사이즈 도구',
    metaDesc: '서버 전송 0KB, 개인정보 100% 보호. 취업 이력서 3x4cm, 여권 3.5x4.5cm 사진 규격 리사이즈 및 이미지 용량(KB/MB) 압축. ZIP 일괄 다운로드 지원.',
    title: '안심 사진 압축 & 규격 리사이즈',
    desc: '주민번호나 얼굴 사진이 외부 서버에 저장될 걱정 없이, 내 브라우저(PC/스마트폰)에서 100% 안전하게 즉시 변환합니다.',
    subNotice: '📄 이력서(3x4cm) • 🛂 여권(3.5x4.5cm) • 🏛️ 정부24/공공기관 첨부서류 용량 맞춤 등 원클릭 지원',
    tabCompress: '🗜️ 1. 파일 용량 줄이기 (압축)',
    tabResize: '📐 2. 사진 규격 맞추기 (리사이즈)',
    compressPresetTitle: '⚡ 용량 압축 빠른 프리셋',
    compressPresetSub: '사진 크기(해상도)는 최대한 보존하며 바이트만 절감',
    presetStd: '🎯 일반 표준 압축',
    presetStdDesc: '품질 80% • JPG',
    presetHigh: '🚀 초고효율 압축',
    presetHighDesc: '품질 60% • WebP',
    presetGov: '🏛️ 정부24 서류용',
    presetGovDesc: '1MB 이하 안전 압축',
    presetResume: '📄 취업사이트 서류',
    presetResumeDesc: '100KB~300KB 타겟',
    resizePresetTitle: '⚡ 증명사진 & 제출 규격 프리셋',
    resizePresetSub: '제출처 요구 가로 x 세로 픽셀 치수에 자동 맞춤',
    resizeResume: '📄 취업/이력서 사진',
    resizeResumeDesc: '3x4cm (354x472px)',
    resizePassport: '🛂 여권/주민등록증',
    resizePassportDesc: '3.5x4.5cm (413x531px)',
    resizeGov: '🏛️ 서류 원본축소',
    resizeGovDesc: '가로 최대 1600px',
    resizeSns: '📱 SNS 정방형',
    resizeSnsDesc: '1:1 (1080x1080px)',
    dropTitle: '증명사진이나 서류 이미지를 드래그하거나 클릭하세요 (여러 장 동시 가능)',
    dropSub: '서버 업로드 용량 제한 없음 • 내 PC 메모리에서 100% 안전하게 즉시 연산',
    saveFormat: '저장 포맷',
    formatJpg: 'JPG / JPEG (공공기관 및 취업포털 표준)',
    formatWebp: 'WebP (초고압축 웹 표준 권장)',
    formatPng: 'PNG (무손실 선명도 유지)',
    qualityLabel: '화질 / 압축율',
    processedTotalPrefix: '총',
    processedTotalSuffix: '개의 사진 처리 완료',
    downloadZip: '전체 ZIP 파일 다운로드',
    clearAll: '모두 비우기',
    resolution: '해상도',
    savedRate: '절감',
    downloadSingle: '다운로드',
    processing: '처리 중...',
    delete: '삭제',
    faqTitle: '자주 묻는 질문 (FAQ)',
    faq1Q: 'Q. 용량 압축(Compress)과 규격 리사이즈(Resize)는 어떻게 다른가요?',
    faq1A: '용량 압축은 사진 크기(픽셀 치수)를 유지한 채 파일 바이트(KB/MB)만 줄여 500KB나 1MB 등 제출 제한에 맞출 때 사용합니다. 반면 규격 리사이즈는 취업 이력서(3x4cm)나 여권(3.5x4.5cm) 등 정해진 규격 픽셀 비율로 사진 크기 자체를 변환할 때 사용합니다.',
    faq2Q: 'Q. 여러 장의 사진을 한 번에 줄이고 ZIP 파일로 받을 수 있나요?',
    faq2A: '네! 여러 장의 이미지를 동시에 선택하거나 드래그하여 올리면 각각 개별 다운로드하거나, [📦 전체 ZIP 파일 다운로드] 버튼을 통해 한 번의 압축 파일로 묶어서 다운로드하실 수 있습니다.',
    faq3Q: 'Q. Vercel이나 서버의 업로드 용량 제한에 걸리지 않나요?',
    faq3A: '이 웹사이트는 정적(Static SPA) 방식으로 배포되어 있어 서버로 파일을 전송하지 않습니다. 모든 작업은 고객님의 컴퓨터나 스마트폰 웹브라우저 메모리 안에서만 실행되므로, 일반 클라우드 서버의 4.5MB 업로드 제한을 전혀 받지 않습니다.'
  },
  en: {
    headerTitle: 'Zero-Upload Media Tools',
    headerSub: 'ZeroUpload Media Tools',
    headerBadge: '🔒 100% Client-Side Processing (0KB Server Upload)',
    metaTitle: 'Zero-Upload Photo Resizer & Compressor - FastPic',
    metaDesc: 'Resize photos for passports, resumes (3x4cm) & government submissions directly in your browser. Zero bytes uploaded to remote servers. Bulk ZIP export.',
    title: 'Zero-Upload Photo Resizer & Compressor',
    desc: 'Confidential portrait or ID photos never leave your device. Processed 100% client-side inside your browser sandbox.',
    subNotice: '📄 Resume (3x4cm) • 🛂 Passport (3.5x4.5cm) • 🏛️ Official Document Compress & Resize',
    tabCompress: '🗜️ 1. Compress File Size',
    tabResize: '📐 2. Resize Dimensions',
    compressPresetTitle: '⚡ Quick Compression Presets',
    compressPresetSub: 'Preserve pixel resolution while trimming byte size',
    presetStd: '🎯 Standard Balanced',
    presetStdDesc: '80% Quality • JPG',
    presetHigh: '🚀 Maximum Compress',
    presetHighDesc: '60% Quality • WebP',
    presetGov: '🏛️ Official Submissions',
    presetGovDesc: 'Under 1MB target',
    presetResume: '📄 Job Portals',
    presetResumeDesc: '100KB~300KB target',
    resizePresetTitle: '⚡ ID Photo & Document Dimensions',
    resizePresetSub: 'Automatically fit required width × height dimensions',
    resizeResume: '📄 Job / Resume Photo',
    resizeResumeDesc: '3x4cm (354x472px)',
    resizePassport: '🛂 Passport / National ID',
    resizePassportDesc: '3.5x4.5cm (413x531px)',
    resizeGov: '🏛️ Doc Scan Scaler',
    resizeGovDesc: 'Max width 1600px',
    resizeSns: '📱 SNS Square',
    resizeSnsDesc: '1:1 (1080x1080px)',
    dropTitle: 'Drop portrait or document photos here, or click to browse',
    dropSub: 'No file size limits • Processed entirely in client memory',
    saveFormat: 'Target Format',
    formatJpg: 'JPG / JPEG (Portal standard)',
    formatWebp: 'WebP (Modern web recommended)',
    formatPng: 'PNG (Lossless sharpness)',
    qualityLabel: 'Quality / Compression Ratio',
    processedTotalPrefix: 'Total',
    processedTotalSuffix: 'photos ready',
    downloadZip: 'Download All (ZIP)',
    clearAll: 'Clear all',
    resolution: 'Resolution',
    savedRate: 'reduced',
    downloadSingle: 'Download',
    processing: 'Processing...',
    delete: 'Delete',
    faqTitle: 'Frequently Asked Questions (FAQ)',
    faq1Q: 'Q. What is the difference between Compress and Resize?',
    faq1A: 'Compression reduces file byte size (KB/MB) while keeping pixel dimensions unchanged. Resizing changes the actual canvas width and height to match official specifications such as resumes or passports.',
    faq2Q: 'Q. Can I process multiple photos and download as a ZIP file?',
    faq2A: 'Yes! Select multiple photos at once and download them individually or as a single combined ZIP archive.',
    faq3Q: 'Q. Is there any server file size upload quota?',
    faq3A: 'No. Since this tool runs 100% locally in your browser memory without transmitting bytes to any cloud server, you are not subject to server payload limits.'
  }
};
