import { writable } from 'svelte/store';

export type Lang = 'en' | 'fr' | 'de' | 'es' | 'vi' | 'ja' | 'ko';

export const currentLang = writable<Lang>('en');

export const translations = {
  en: {
    siteTitle: 'PureQR Studio',
    subBrand: 'Permanent Static QR Code Generator · No Redirects',
    badge: '🔒 100% In-Browser · Never Expires · 0KB Server Upload',
    heroTitle: 'Permanent, Direct QR Codes. Zero Redirects. Never Expires.',
    heroSub: 'Create high-resolution vector QR codes for websites, WiFi direct connect, vCards & WhatsApp. 100% in-browser generation with zero middleman traps.',
    tabUrl: '🔗 Website URL',
    tabWifi: '📶 WiFi Direct',
    tabVcard: '📇 Contact (vCard)',
    tabWhatsapp: '💬 WhatsApp',
    tabEmail: '✉️ Email',
    tabText: '📝 Plain Text',
    urlPlaceholder: 'https://yourwebsite.com',
    wifiSsid: 'Network Name (SSID)',
    wifiPass: 'Password',
    wifiSec: 'Security',
    wifiHidden: 'Hidden Network',
    vcardName: 'Full Name',
    vcardPhone: 'Phone Number',
    vcardEmail: 'Email',
    vcardOrg: 'Company / Organization',
    vcardTitle: 'Job Title',
    waPhone: 'Phone Number (with country code, e.g. 14155552671)',
    waMsg: 'Pre-filled message (optional)',
    emailTo: 'Recipient Email',
    emailSub: 'Subject',
    emailBody: 'Body',
    textPlaceholder: 'Enter any text, crypto wallet address, or serial number...',
    styleTitle: '🎨 Custom Styling',
    fgColor: 'QR Color',
    bgColor: 'Background',
    eccLevel: 'Error Correction',
    eccDesc: 'High allows scanning even if 30% damaged or with a logo overlay.',
    eccL: 'Low (7%)',
    eccM: 'Medium (15%)',
    eccQ: 'Quartile (25%)',
    eccH: 'High (30% - Best for Print)',
    downloadSvg: '⬇️ Download Vector SVG (Print Ready)',
    downloadPng: '⬇️ Download High-Res PNG (2048px)',
    copyBtn: '📋 Copy QR Image',
    copiedText: 'Copied to clipboard!',
    scamWarningTitle: '🛡️ Why PureQR Never Expires',
    scamWarningDesc: 'Most free generators encode a redirect link (e.g. qr.biz/1234) and hold your printed menus or business cards hostage for $15/month after 14 days. PureQR encodes 100% direct raw data directly into the matrix in your local browser memory. It is physically impossible for this code to expire.',
    faqTitle: 'Frequently Asked Questions',
    faq1Q: 'Q. Is this a free static QR code generator with no expiration or redirect?',
    faq1A: 'A. Yes. PureQR encodes the destination directly in a permanent static QR graphic, with no shortener, redirect server, subscription, or expiration date.',
    faq2Q: 'Q. Is it safe to generate WiFi and contact QR codes here?',
    faq2A: 'A. Yes. WiFi, vCard, URL, WhatsApp, email, and text QR data is rendered in your browser. 0KB is uploaded to any server.'
  },
  ko: {
    siteTitle: '퓨어 QR 스튜디오',
    subBrand: '영구 정적 QR 코드 생성기 · 리다이렉트 제로',
    badge: '🔒 100% 로컬 브라우저 연산 · 영구 불변 · 서버 전송 0KB',
    heroTitle: '인질극 없는 진짜 영구 QR 코드. 만료 제로.',
    heroSub: 'URL, 와이파이 자동 접속, 전자 명함(vCard), 카카오/왓츠앱 링크를 100% 브라우저 내에서 안전하게 생성하세요. 인쇄용 고해상도 벡터 SVG 즉시 지원.',
    tabUrl: '🔗 웹사이트 URL',
    tabWifi: '📶 와이파이 원클릭 접속',
    tabVcard: '📇 전자 명함 (vCard)',
    tabWhatsapp: '💬 메신저 / 왓츠앱',
    tabEmail: '✉️ 이메일 작성',
    tabText: '📝 일반 텍스트',
    urlPlaceholder: 'https://내사이트.com',
    wifiSsid: '와이파이 이름 (SSID)',
    wifiPass: '비밀번호',
    wifiSec: '보안 방식',
    wifiHidden: '숨김 네트워크',
    vcardName: '이름 (성명)',
    vcardPhone: '전화번호',
    vcardEmail: '이메일 주소',
    vcardOrg: '회사 / 소속',
    vcardTitle: '직함 / 부서',
    waPhone: '국가번호 포함 전화번호 (예: 821012345678)',
    waMsg: '자동 입력 메시지 (선택)',
    emailTo: '받는 사람 이메일',
    emailSub: '제목',
    emailBody: '본문 내용',
    textPlaceholder: '텍스트, 계좌번호, 암호화폐 지갑 주소 등...',
    styleTitle: '🎨 디자인 커스터마이징',
    fgColor: 'QR 코드 색상',
    bgColor: '배경 색상',
    eccLevel: '오류 복원율 (ECC)',
    eccDesc: '복원율이 높으면 QR이 일부 손상되거나 중앙에 로고를 얹어도 스캔됩니다.',
    eccL: '낮음 (7%)',
    eccM: '표준 (15%)',
    eccQ: '높음 (25%)',
    eccH: '최고 (30% - 인쇄물 추천)',
    downloadSvg: '⬇️ 벡터 SVG 다운로드 (인쇄/출력용)',
    downloadPng: '⬇️ 초고화질 PNG 다운로드 (2048px)',
    copyBtn: '📋 이미지 클립보드 복사',
    copiedText: '클립보드에 복사되었습니다!',
    scamWarningTitle: '🛡️ 퓨어 QR이 100% 영구 불변인 이유',
    scamWarningDesc: '시중의 무료 QR 사이트 대부분은 자체 리다이렉트 주소를 심어두고 인쇄 14일 뒤 연결을 차단하여 월 2만 원 결제를 유도합니다. 퓨어 QR은 사용자의 순수 원본 데이터를 브라우저 메모리에서 매트릭스에 직접 각인하므로, 서버 차단이나 유효기간 만료가 구조적으로 불가능합니다.',
    faqTitle: '자주 묻는 질문 (FAQ)',
    faq1Q: 'Q. 인쇄 후 시간이 지나면 QR 코드가 만료되나요?',
    faq1A: 'A. 절대 만료되지 않습니다. 중계 서버 없이 데이터 자체가 이미지 패턴으로 물리적으로 인코딩된 정적(Static) QR 코드입니다.',
    faq2Q: 'Q. 와이파이 비번이나 명함 정보를 입력해도 안전한가요?',
    faq2A: 'A. 네, 외부 서버로 단 1바이트도 전송되지 않으며 고객님의 기기 내부에서만 연산되므로 민감 정보도 안심하고 제작하실 수 있습니다.'
  },
  fr: {
    siteTitle: 'PureQR Studio',
    subBrand: 'Générateur QR Code Statique Permanent · Sans Redirection',
    badge: '🔒 100% Côté Navigateur · N\'expire Jamais · 0 Ko Serveur',
    heroTitle: 'QR Codes Permanents & Directs. Zéro Redirection. Jamais d\'Expiration.',
    heroSub: 'Générez des QR codes vectoriels pour sites web, connexion Wi-Fi directe, vCards & WhatsApp. 100% local, sans abonnement caché.',
    tabUrl: '🔗 URL Site Web',
    tabWifi: '📶 Connexion Wi-Fi Directe',
    tabVcard: '📇 Contact (vCard)',
    tabWhatsapp: '💬 WhatsApp',
    tabEmail: '✉️ E-mail',
    tabText: '📝 Texte Brut',
    urlPlaceholder: 'https://votresite.fr',
    wifiSsid: 'Nom du réseau (SSID)',
    wifiPass: 'Mot de passe',
    wifiSec: 'Sécurité',
    wifiHidden: 'Réseau masqué',
    vcardName: 'Nom complet',
    vcardPhone: 'Téléphone',
    vcardEmail: 'E-mail',
    vcardOrg: 'Entreprise / Organisation',
    vcardTitle: 'Poste / Titre',
    waPhone: 'Numéro avec indicatif (ex. 33612345678)',
    waMsg: 'Message pré-rempli (facultatif)',
    emailTo: 'Destinataire',
    emailSub: 'Objet',
    emailBody: 'Message',
    textPlaceholder: 'Entrez un texte, une adresse crypto...',
    styleTitle: '🎨 Personnalisation Graphique',
    fgColor: 'Couleur du QR',
    bgColor: 'Arrière-plan',
    eccLevel: 'Correction d\'erreur',
    eccDesc: 'Permet la lisibilité même en cas de pliure ou salissure.',
    eccL: 'Faible (7%)',
    eccM: 'Moyen (15%)',
    eccQ: 'Élevé (25%)',
    eccH: 'Maximum (30% - Idéal Impression)',
    downloadSvg: '⬇️ Télécharger SVG Vectoriel (Pour impression)',
    downloadPng: '⬇️ Télécharger PNG Haute Résolution (2048px)',
    copyBtn: '📋 Copier l\'image',
    copiedText: 'Copié dans le presse-papiers !',
    scamWarningTitle: '🛡️ Pourquoi PureQR n\'expire jamais',
    scamWarningDesc: 'La plupart des générateurs gratuits utilisent des liens de redirection pour bloquer vos menus imprimés après 14 jours et réclamer 15€/mois. PureQR encode directement vos données dans la matrice en local. Aucun serveur ne peut bloquer votre QR code.',
    faqTitle: 'Foire Aux Questions (FAQ)',
    faq1Q: 'Q. Ce QR code risque-t-il d\'expirer un jour ?',
    faq1A: 'A. Jamais. C\'est un QR code statique direct sans intermédiaire.',
    faq2Q: 'Q. Mes identifiants Wi-Fi sont-ils sécurisés ?',
    faq2A: 'A. 100% sécurisés. Le calcul se fait dans la RAM de votre navigateur, zéro envoi externe.'
  },
  de: {
    siteTitle: 'PureQR Studio',
    subBrand: 'Dauerhafter Statischer QR-Code Generator · Ohne Weiterleitung',
    badge: '🔒 100% Im Browser · Läuft Nie Ab · 0 KB Server-Upload',
    heroTitle: 'Dauerhafte, Echte QR-Codes. Keine Fallen. Nie Wieder Abo-Kosten.',
    heroSub: 'Erstellen Sie hochauflösende Vektor-QR-Codes für Websites, WLAN-Sofortverbindung, vCards und WhatsApp völlig ohne Server-Tracking.',
    tabUrl: '🔗 Website-URL',
    tabWifi: '📶 WLAN-Direktverbindung',
    tabVcard: '📇 Kontaktkarte (vCard)',
    tabWhatsapp: '💬 WhatsApp',
    tabEmail: '✉️ E-Mail',
    tabText: '📝 Reiner Text',
    urlPlaceholder: 'https://ihre-website.de',
    wifiSsid: 'Netzwerkname (SSID)',
    wifiPass: 'WLAN-Schlüssel',
    wifiSec: 'Verschlüsselung',
    wifiHidden: 'Verborgenes Netzwerk',
    vcardName: 'Vollständiger Name',
    vcardPhone: 'Telefonnummer',
    vcardEmail: 'E-Mail-Adresse',
    vcardOrg: 'Firma / Organisation',
    vcardTitle: 'Position',
    waPhone: 'Telefonnummer mit Ländervorwahl',
    waMsg: 'Vorgefertigte Nachricht (optional)',
    emailTo: 'Empfänger',
    emailSub: 'Betreff',
    emailBody: 'Nachricht',
    textPlaceholder: 'Beliebigen Text oder Krypto-Adresse eingeben...',
    styleTitle: '🎨 Stil & Anpassung',
    fgColor: 'QR-Farbe',
    bgColor: 'Hintergrund',
    eccLevel: 'Fehlerkorrektur (ECC)',
    eccDesc: 'Garantiert Scannen auch bei Beschädigung oder Logo-Overlay.',
    eccL: 'Niedrig (7%)',
    eccM: 'Standard (15%)',
    eccQ: 'Hoch (25%)',
    eccH: 'Maximal (30% - Druckqualität)',
    downloadSvg: '⬇️ Vektor-SVG herunterladen (Druckbereit)',
    downloadPng: '⬇️ Hochauflösendes PNG (2048px)',
    copyBtn: '📋 Bild in Zwischenablage kopieren',
    copiedText: 'Kopiert!',
    scamWarningTitle: '🛡️ Warum PureQR niemals verfällt',
    scamWarningDesc: 'Typische "kostenlose" QR-Generatoren verlinken über eigene Tracking-Server und verlangen nach zwei Wochen horrende Monatsabos. PureQR codiert Ihre Rohdaten direkt und unwiderruflich in das Pixelmuster ein.',
    faqTitle: 'Häufig gestellte Fragen (FAQ)',
    faq1Q: 'Q. Kann dieser QR-Code jemals ablaufen?',
    faq1A: 'A. Nein, niemals. Die Daten sind direkt im Bild fest verankert.',
    faq2Q: 'Q. Werden meine Daten auf Servern gespeichert?',
    faq2A: 'A. Nein, 100% clientseitige Berechnung in Ihrem Browser.'
  },
  es: {
    siteTitle: 'PureQR Studio',
    subBrand: 'Generador de Códigos QR Estáticos Permanentes · Sin Redirecciones',
    badge: '🔒 100% En Navegador · No Caduca Nunca · 0KB Servidor',
    heroTitle: 'Códigos QR Directos y Permanentes. Sin Trampas ni Caducidad.',
    heroSub: 'Crea códigos QR vectoriales para páginas web, conexión WiFi directa, vCards y WhatsApp sin intermediarios.',
    tabUrl: '🔗 Enlace Web',
    tabWifi: '📶 WiFi Directo',
    tabVcard: '📇 Contacto (vCard)',
    tabWhatsapp: '💬 WhatsApp',
    tabEmail: '✉️ Correo',
    tabText: '📝 Texto Libre',
    urlPlaceholder: 'https://tusitio.es',
    wifiSsid: 'Nombre de red (SSID)',
    wifiPass: 'Contraseña',
    wifiSec: 'Seguridad',
    wifiHidden: 'Red oculta',
    vcardName: 'Nombre completo',
    vcardPhone: 'Teléfono',
    vcardEmail: 'Correo electrónico',
    vcardOrg: 'Empresa / Organización',
    vcardTitle: 'Puesto',
    waPhone: 'Número con prefijo internacional',
    waMsg: 'Mensaje predeterminado',
    emailTo: 'Destinatario',
    emailSub: 'Asunto',
    emailBody: 'Cuerpo del mensaje',
    textPlaceholder: 'Cualquier texto o dirección crypto...',
    styleTitle: '🎨 Personalización',
    fgColor: 'Color QR',
    bgColor: 'Fondo',
    eccLevel: 'Corrección de errores',
    eccDesc: 'Permite leer el código aunque esté parcialmente cubierto o dañado.',
    eccL: 'Bajo (7%)',
    eccM: 'Medio (15%)',
    eccQ: 'Alto (25%)',
    eccH: 'Máximo (30% - Ideal Imprenta)',
    downloadSvg: '⬇️ Descargar SVG Vectorial (Imprenta)',
    downloadPng: '⬇️ Descargar PNG Alta Resolución (2048px)',
    copyBtn: '📋 Copiar Imagen',
    copiedText: '¡Copiado!',
    scamWarningTitle: '🛡️ Por qué PureQR nunca expira',
    scamWarningDesc: 'La mayoría de generadores usan enlaces de redirección para bloquear tus folletos impresos y pedir suscripciones caras. PureQR graba directamente tus datos en los píxeles desde tu navegador.',
    faqTitle: 'Preguntas Frecuentes',
    faq1Q: 'Q. ¿Caducará este código QR?',
    faq1A: 'A. Nunca. Es un código QR estático permanente.',
    faq2Q: 'Q. ¿Se envían mis contraseñas o datos a internet?',
    faq2A: 'A. No, todo se calcula 100% en la memoria de tu dispositivo.'
  },
  vi: {
    siteTitle: 'PureQR Studio',
    subBrand: 'Tạo Mã QR Tĩnh Vĩnh Viễn · Không Chuyển Hướng Lừa Đảo',
    badge: '🔒 100% Trên Trình Duyệt · Không Hết Hạn · 0KB Máy Chủ',
    heroTitle: 'Mã QR Trực Tiếp Vĩnh Viễn. Không Trung Gian. Không Bao Giờ Khóa.',
    heroSub: 'Tạo mã QR vector sắc nét cho Website, kết nối WiFi tự động, danh thiếp vCard và Zalo/WhatsApp 100% an toàn bảo mật.',
    tabUrl: '🔗 Đường Dẫn Web',
    tabWifi: '📶 Quét Vào WiFi',
    tabVcard: '📇 Danh Thiếp (vCard)',
    tabWhatsapp: '💬 WhatsApp / Chat',
    tabEmail: '✉️ Gửi Email',
    tabText: '📝 Văn Bản Tùy Ý',
    urlPlaceholder: 'https://trangweb.vn',
    wifiSsid: 'Tên WiFi (SSID)',
    wifiPass: 'Mật khẩu WiFi',
    wifiSec: 'Bảo mật',
    wifiHidden: 'Mạng ẩn',
    vcardName: 'Họ và tên',
    vcardPhone: 'Số điện thoại',
    vcardEmail: 'Email',
    vcardOrg: 'Công ty / Đơn vị',
    vcardTitle: 'Chức danh',
    waPhone: 'Số điện thoại (kèm mã quốc gia, ví dụ: 84912345678)',
    waMsg: 'Lời nhắn gửi sẵn',
    emailTo: 'Email người nhận',
    emailSub: 'Tiêu đề',
    emailBody: 'Nội dung thư',
    textPlaceholder: 'Nhập nội dung, số tài khoản ngân hàng...',
    styleTitle: '🎨 Tùy Chỉnh Màu Sắc',
    fgColor: 'Màu mã QR',
    bgColor: 'Màu nền',
    eccLevel: 'Khả năng sửa lỗi (ECC)',
    eccDesc: 'Mức cao cho phép quét tốt ngay cả khi mã bị mờ hoặc chèn logo.',
    eccL: 'Thấp (7%)',
    eccM: 'Tiêu chuẩn (15%)',
    eccQ: 'Cao (25%)',
    eccH: 'Cao nhất (30% - Khuyên dùng khi in)',
    downloadSvg: '⬇️ Tải file Vector SVG (Chuẩn in ấn sắc nét)',
    downloadPng: '⬇️ Tải file PNG Cực Nét (2048px)',
    copyBtn: '📋 Sao Chép Ảnh QR',
    copiedText: 'Đã sao chép vào bộ nhớ tạm!',
    scamWarningTitle: '🛡️ Vì sao PureQR không bao giờ hết hạn',
    scamWarningDesc: 'Rất nhiều trang web QR lừa người dùng bằng cách chèn link chuyển hướng rồi khóa mã sau 14 ngày để đòi tiền thuê bao tháng. PureQR mã hóa trực tiếp dữ liệu của bạn vào từng điểm ảnh ngay trên trình duyệt, cam kết vĩnh viễn không thể bị khóa.',
    faqTitle: 'Câu Hỏi Thường Gặp',
    faq1Q: 'Q. Mã QR này có bị hết hạn sau khi in không?',
    faq1A: 'A. Tuyệt đối không. Đây là mã QR tĩnh thật sự, dữ liệu nằm ngay trên ảnh.',
    faq2Q: 'Q. Mật khẩu WiFi và thông tin có bị lộ không?',
    faq2A: 'A. Hoàn toàn không. Xử lý 100% trên máy của bạn, không gửi bất kỳ dữ liệu nào lên mạng.'
  },
  ja: {
    siteTitle: 'PureQR Studio',
    subBrand: '永久静的QRコード生成ツール · リダイレクト詐欺ゼロ',
    badge: '🔒 100% ブラウザ完結 · 永久有効 · サーバー送信0KB',
    heroTitle: '期限切れなし。本当の永久静的QRコード生成。',
    heroSub: 'URL、Wi-Fi自動接続、電子名刺(vCard)、各種SNSリンクを高解像度ベクトルSVGで生成。サブスク請求の心配ゼロ。',
    tabUrl: '🔗 WebサイトURL',
    tabWifi: '📶 Wi-Fiワンタップ接続',
    tabVcard: '📇 連絡先 (vCard)',
    tabWhatsapp: '💬 メッセージ',
    tabEmail: '✉️ メール作成',
    tabText: '📝 テキスト',
    urlPlaceholder: 'https://example.jp',
    wifiSsid: 'Wi-Fiネットワーク名 (SSID)',
    wifiPass: 'パスワード',
    wifiSec: 'セキュリティ方式',
    wifiHidden: '非公開ネットワーク',
    vcardName: '氏名',
    vcardPhone: '電話番号',
    vcardEmail: 'メールアドレス',
    vcardOrg: '会社名・所属',
    vcardTitle: '役職・肩書',
    waPhone: '国番号を含む電話番号（例: 819012345678）',
    waMsg: '初期メッセージ（任意）',
    emailTo: '宛先メールアドレス',
    emailSub: '件名',
    emailBody: '本文',
    textPlaceholder: 'テキスト、口座番号、暗号資産アドレスなど...',
    styleTitle: '🎨 デザインカスタマイズ',
    fgColor: 'QRコードの色',
    bgColor: '背景色',
    eccLevel: '誤り訂正能力 (ECC)',
    eccDesc: '訂正レベルが高いと、汚れやロゴ配置時でも正確に読み取れます。',
    eccL: '低 (7%)',
    eccM: '標準 (15%)',
    eccQ: '高 (25%)',
    eccH: '最高 (30% - 印刷物に最適)',
    downloadSvg: '⬇️ ベクトルSVG保存（印刷・看板用）',
    downloadPng: '⬇️ 高解像度PNG保存 (2048px)',
    copyBtn: '📋 画像をクリップボードにコピー',
    copiedText: 'コピーしました！',
    scamWarningTitle: '🛡️ PureQRが永久に失効しない理由',
    scamWarningDesc: '一般的な「無料QRサイト」の多くは独自のリダイレクトURLを埋め込み、印刷後14日ほどで接続を止め高額サブスクを要求します。PureQRはお客様のブラウザ内だけで直接データをドットに焼き付けるため、後から失効することは物理的に不可能です。',
    faqTitle: 'よくある質問 (FAQ)',
    faq1Q: 'Q. 印刷後にQRコードが無効になることはありますか？',
    faq1A: 'A. 一切ありません。中継サーバーを持たない完全な静的QRコードです。',
    faq2Q: 'Q. Wi-Fiパスワードや名刺情報を入力しても安全ですか？',
    faq2A: 'A. 完全に安全です。すべての生成処理はブラウザのRAM内で完結し、サーバー送信は0バイトです。'
  }
};
