import { writable } from 'svelte/store';

export type Lang = 'en' | 'fr' | 'de' | 'es' | 'vi' | 'ja' | 'ko';

export const currentLang = writable<Lang>('en');

export const translations = {
  en: {
    siteTitle: 'EXIF Privacy Scrubber',
    subBrand: 'Photo GPS & Metadata Stripper · 100% In-Browser',
    badge: '🔒 100% In-Browser · 0KB Server Upload',
    heroTitle: 'Strip Hidden GPS & Camera Info From Your Photos',
    heroSub: 'Smartphone photos contain your exact home address coordinates, device serial numbers, and timestamps. Remove all tracking metadata in your browser before posting online.',
    dropzoneTitle: 'Drag & Drop Photos Here',
    dropzoneSub: 'Supports JPEG, PNG, WebP · Multiple files allowed · Zero server upload',
    dropzoneBtn: 'Browse Files',
    batchActions: 'Batch Actions',
    downloadZipBtn: '📦 Download All Cleaned (.ZIP)',
    clearAllBtn: 'Clear All',
    filesCount: 'Photos Processed',
    statusCleaned: 'Protected (0 Metadata)',
    gpsFound: 'GPS Location Removed',
    cameraFound: 'Camera Details Stripped',
    downloadBtn: '⬇️ Download Cleaned',
    privacyGuaranteeTitle: '🛡️ Why Stripping EXIF Before Sharing Matters',
    privacyGuaranteeDesc: 'When you take a photo on an iPhone or Android, it silently embeds your exact latitude/longitude GPS location, timestamp, and device model inside the EXIF header. When posted to Reddit, forums, or classifieds, anyone can view your home address. This tool strips 100% of metadata directly inside your browser memory without uploading a single byte to any server.',
    faqTitle: 'Frequently Asked Questions',
    faq1Q: 'Q. How do I remove GPS location and EXIF metadata from photos?',
    faq1A: 'A. Add your JPG, PNG, or WebP photos, then download each cleaned image or the ZIP export. The browser removes hidden GPS, camera, and timestamp metadata locally.',
    faq2Q: 'Q. Are my private photos uploaded to your server?',
    faq2A: 'A. Never. EXIF scrubbing runs in your browser with the local Canvas/Blob APIs. You can disconnect your internet and it still works.'
  },
  ko: {
    siteTitle: '사진 위치(GPS) & EXIF 메타데이터 제거기',
    subBrand: '사진 개인정보 및 촬영 위치 영구 삭제 · 100% 로컬',
    badge: '🔒 100% 브라우저 메모리 연산 · 서버 전송 0KB',
    heroTitle: '사진 속 숨겨진 집 주소(GPS)와 촬영 정보를 1초 만에 삭제',
    heroSub: '스마트폰으로 찍은 사진에는 집 주소 위도/경도, 기종, 촬영 시각이 고스란히 저장되어 있습니다. 중고거래나 커뮤니티에 올리기 전 안전하게 제거하세요.',
    dropzoneTitle: '사진을 여기에 드래그하거나 클릭하세요',
    dropzoneSub: 'JPG, PNG, WebP 지원 · 여러 장 일괄 처리 · 서버 업로드 0바이트',
    dropzoneBtn: '사진 파일 선택',
    batchActions: '일괄 작업',
    downloadZipBtn: '📦 안전한 사진 전체 다운로드 (.ZIP)',
    clearAllBtn: '전체 비우기',
    filesCount: '처리된 사진',
    statusCleaned: '개인정보 완전 제거됨',
    gpsFound: '위치 정보(GPS) 삭제 완료',
    cameraFound: '기기/촬영 정보 삭제 완료',
    downloadBtn: '⬇️ 정제본 다운로드',
    privacyGuaranteeTitle: '🛡️ 사진 메타데이터(EXIF) 삭제가 필수인 이유',
    privacyGuaranteeDesc: '스마트폰 카메라로 촬영한 사진에는 눈에 보이지 않지만 상세 주소(위도/경도 GPS), 촬영 일시, 폰 일련번호가 기록됩니다. 중고나라, 당근마켓, 디시인사이드, 레딧 등에 그대로 업로드하면 거주지 위치가 노출될 수 있습니다. 본 도구는 브라우저 내부 캔버스 엔진에서 픽셀만 남기고 모든 메타데이터를 영구 소멸시킵니다.',
    faqTitle: '자주 묻는 질문 (FAQ)',
    faq1Q: 'Q. 메타데이터를 지우면 사진 화질이 떨어지나요?',
    faq1A: 'A. 시각적인 화질 손실 없이 원본 해상도를 유지하며, 숨겨진 텍스트 메타데이터 정보만 안전하게 분리 파기합니다.',
    faq2Q: 'Q. 제 사진이 외부 서버로 업로드되나요?',
    faq2A: 'A. 절대 업로드되지 않습니다. 인터넷 연결을 끊은 오프라인 상태에서도 작동할 만큼 100% 귀하의 기기 내부에서만 처리됩니다.'
  },
  fr: {
    siteTitle: 'EXIF Privacy Scrubber',
    subBrand: 'Suppression des métadonnées GPS et EXIF · 100% Navigateur',
    badge: '🔒 100% En Local · 0 Ko Transféré',
    heroTitle: 'Supprimez le GPS et les Infos Cachées de Vos Photos',
    heroSub: 'Vos photos de smartphone contiennent vos coordonnées GPS précises et l\'historique de votre appareil. Nettoyez vos clichés avant de les publier.',
    dropzoneTitle: 'Glissez-déposez vos photos ici',
    dropzoneSub: 'Prend en charge JPEG, PNG, WebP · Traitement par lot · Zéro serveur',
    dropzoneBtn: 'Parcourir les fichiers',
    batchActions: 'Actions groupées',
    downloadZipBtn: '📦 Télécharger Tout Nettoyé (.ZIP)',
    clearAllBtn: 'Effacer tout',
    filesCount: 'Photos traitées',
    statusCleaned: 'Protégé (Métadonnées purgées)',
    gpsFound: 'Localisation GPS effacée',
    cameraFound: 'Infos appareil photo purgées',
    downloadBtn: '⬇️ Télécharger Photo Propre',
    privacyGuaranteeTitle: '🛡️ Pourquoi supprimer les métadonnées EXIF ?',
    privacyGuaranteeDesc: 'Chaque photo prise au smartphone contient la localisation GPS exacte de votre domicile. Ce nettoyeur supprime 100% des métadonnées directement dans la mémoire de votre navigateur sans aucun envoi vers un serveur.',
    faqTitle: 'Foire Aux Questions',
    faq1Q: 'Q. Cela réduit-il la qualité visuelle de la photo ?',
    faq1A: 'A. Non, les pixels sont préservés à qualité maximale sans compression destructive.',
    faq2Q: 'Q. Mes photos personnelles sont-elles envoyées sur un serveur ?',
    faq2A: 'A. Jamais. Le traitement est 100% local dans la RAM de votre appareil.'
  },
  de: {
    siteTitle: 'EXIF Privacy Scrubber',
    subBrand: 'GPS- & Metadaten-Entferner für Fotos · 100% Im Browser',
    badge: '🔒 100% Im Browser · 0 KB Server-Upload',
    heroTitle: 'Entfernen Sie versteckte GPS-Daten aus Ihren Fotos',
    heroSub: 'Smartphone-Fotos enthalten Ihren genauen Wohnort als GPS-Koordinaten. Schützen Sie Ihre Privatsphäre vor dem Online-Teilen.',
    dropzoneTitle: 'Fotos hierher ziehen oder klicken',
    dropzoneSub: 'Unterstützt JPEG, PNG, WebP · Mehrfachauswahl · Ohne Server-Upload',
    dropzoneBtn: 'Dateien auswählen',
    batchActions: 'Stapelverarbeitung',
    downloadZipBtn: '📦 Alle Bereinigten Herunterladen (.ZIP)',
    clearAllBtn: 'Alles löschen',
    filesCount: 'Fotos verarbeitet',
    statusCleaned: 'Geschützt (0 Metadaten)',
    gpsFound: 'GPS-Standort entfernt',
    cameraFound: 'Kamerainfos gelöscht',
    downloadBtn: '⬇️ Bereinigtes Foto laden',
    privacyGuaranteeTitle: '🛡️ Warum EXIF-Metadaten gefährlich sein können',
    privacyGuaranteeDesc: 'Fotos speichern oft exakte Längen- und Breitengrade Ihres Wohnorts. Dieses Werkzeug entfernt alle EXIF- und GPS-Einträge vollständig lokal in Ihrem Browser.',
    faqTitle: 'Häufig gestellte Fragen (FAQ)',
    faq1Q: 'Q. Verschlechtert sich die Bildqualität?',
    faq1A: 'A. Nein, die sichtbaren Bildpixel bleiben bei höchster Qualität erhalten.',
    faq2Q: 'Q. Werden Fotos auf einen Server hochgeladen?',
    faq2A: 'A. Niemals. Alle Vorgänge laufen offline in Ihrem Browser ab.'
  },
  es: {
    siteTitle: 'EXIF Privacy Scrubber',
    subBrand: 'Eliminador de GPS y Metadatos en Fotos · 100% En Navegador',
    badge: '🔒 100% En Navegador · 0KB al Servidor',
    heroTitle: 'Elimina las Coordenadas GPS y Datos Ocultos de tus Fotos',
    heroSub: 'Las fotos de tu móvil incluyen la dirección exacta de tu casa y modelo de cámara. Limpia tus imágenes antes de subirlas a internet.',
    dropzoneTitle: 'Arrastra y suelta tus fotos aquí',
    dropzoneSub: 'Compatible con JPEG, PNG, WebP · Selección múltiple · Sin servidores',
    dropzoneBtn: 'Seleccionar fotos',
    batchActions: 'Acciones por lote',
    downloadZipBtn: '📦 Descargar Todas Limpias (.ZIP)',
    clearAllBtn: 'Limpiar lista',
    filesCount: 'Fotos procesadas',
    statusCleaned: 'Protegido (Sin metadatos)',
    gpsFound: 'Ubicación GPS eliminada',
    cameraFound: 'Datos de cámara borrados',
    downloadBtn: '⬇️ Descargar Limpia',
    privacyGuaranteeTitle: '🛡️ Por qué es importante limpiar el EXIF',
    privacyGuaranteeDesc: 'Al compartir fotos en foros o redes, cualquiera puede extraer tus coordenadas GPS exactas. Nuestra herramienta purga los metadatos directamente en la memoria de tu dispositivo.',
    faqTitle: 'Preguntas Frecuentes',
    faq1Q: 'Q. ¿Afecta a la calidad de la imagen?',
    faq1A: 'A. No, mantiene la máxima resolución y píxeles visibles.',
    faq2Q: 'Q. ¿Se suben mis fotos a algún sitio?',
    faq2A: 'A. Nunca. Funciona 100% en local en tu navegador.'
  },
  vi: {
    siteTitle: 'EXIF Privacy Scrubber',
    subBrand: 'Xóa Vị Trí GPS & Thông Tin Ẩn Của Ảnh · 100% Trình Duyệt',
    badge: '🔒 100% Trên Trình Duyệt · 0KB Máy Chủ',
    heroTitle: 'Xóa Sạch Tọa Độ GPS & Thông Tin Thiết Bị Khỏi Ảnh',
    heroSub: 'Ảnh chụp bằng điện thoại chứa vị trí nhà riêng và số sê-ri máy. Xóa sạch mọi siêu dữ liệu EXIF trước khi đăng lên mạng xã hội.',
    dropzoneTitle: 'Kéo thả ảnh vào đây hoặc nhấp để chọn',
    dropzoneSub: 'Hỗ trợ JPEG, PNG, WebP · Xử lý nhiều ảnh cùng lúc · Không tải lên mạng',
    dropzoneBtn: 'Chọn tệp ảnh',
    batchActions: 'Thao tác hàng loạt',
    downloadZipBtn: '📦 Tải Tất Cả Ảnh Sạch (.ZIP)',
    clearAllBtn: 'Xóa danh sách',
    filesCount: 'Ảnh đã xử lý',
    statusCleaned: 'Đã bảo vệ (Xóa sạch EXIF)',
    gpsFound: 'Đã xóa tọa độ GPS',
    cameraFound: 'Đã xóa thông tin máy ảnh',
    downloadBtn: '⬇️ Tải Ảnh Đã Xóa EXIF',
    privacyGuaranteeTitle: '🛡️ Vì sao cần xóa siêu dữ liệu EXIF trước khi chia sẻ',
    privacyGuaranteeDesc: 'Khi bạn chụp ảnh, camera điện thoại sẽ tự động ghim vị trí kinh độ/vĩ độ chính xác của bạn vào file. Khi đăng lên diễn đàn hay chợ trực tuyến, người khác có thể soi ra địa chỉ nhà bạn. Công cụ này làm sạch 100% dữ liệu ẩn ngay trên máy tính của bạn.',
    faqTitle: 'Câu Hỏi Thường Gặp',
    faq1Q: 'Q. Việc xóa EXIF có làm giảm chất lượng ảnh không?',
    faq1A: 'A. Hoàn toàn không. Toàn bộ điểm ảnh gốc được giữ nguyên độ nét tối đa.',
    faq2Q: 'Q. Ảnh của tôi có bị tải lên máy chủ nào không?',
    faq2A: 'A. Không bao giờ. Mọi thao tác diễn ra trực tiếp trong RAM trình duyệt của bạn.'
  },
  ja: {
    siteTitle: 'EXIF Privacy Scrubber',
    subBrand: '写真の位置情報(GPS)・メタデータ削除ツール · 100% ローカル',
    badge: '🔒 100% ブラウザ完結 · サーバー送信0KB',
    heroTitle: '写真に潜む自宅の位置情報(GPS)と撮影情報を瞬時に削除',
    heroSub: 'スマホで撮った写真には撮影場所の緯度経度やカメラ型番が記録されています。SNSやフリマアプリに投稿する前に安全に消去。',
    dropzoneTitle: '写真をここにドラッグ＆ドロップ',
    dropzoneSub: 'JPEG、PNG、WebP対応 · 複数枚の一括処理 · サーバー送信0バイト',
    dropzoneBtn: 'ファイルを選択',
    batchActions: '一括操作',
    downloadZipBtn: '📦 クリーンな写真を一括保存 (.ZIP)',
    clearAllBtn: '一覧をクリア',
    filesCount: '処理済み写真',
    statusCleaned: '個人情報完全削除済み',
    gpsFound: 'GPS位置情報を消去',
    cameraFound: '撮影機器情報を消去',
    downloadBtn: '⬇️ 写真を保存',
    privacyGuaranteeTitle: '🛡️ EXIFメタデータ削除が必要な理由',
    privacyGuaranteeDesc: 'スマホ写真のメタデータには自宅のピンポイントなGPS座標が含まれており、メルカリやSNSに投稿すると自宅が特定されるリスクがあります。当ツールはブラウザのCanvas処理で視覚情報のみを抽出し、メタデータを物理的に消滅させます。',
    faqTitle: 'よくある質問 (FAQ)',
    faq1Q: 'Q. メタデータを消すと画質は劣化しますか？',
    faq1A: 'A. 画質を損なうことなく、非表示のテキスト情報のみを的確に除去します。',
    faq2Q: 'Q. 写真が外部サーバーに送信されることはありますか？',
    faq2A: 'A. 一切ありません。ネットを切断したオフライン状態でも動作します。'
  }
};
