import { writable } from 'svelte/store';

export type Lang = 'vi' | 'ko' | 'en';

export const currentLang = writable<Lang>('vi');

export const translations = {
  vi: {
    siteTitle: 'Cờ Caro Online',
    siteSub: 'Chơi Cờ Caro (Gomoku) 1:1 Thời Gian Thực',
    badgeTop: '🇻🇳 Cờ Caro Trực Tuyến 1:1 (P2P Real-time)',
    heroTitle: 'Cờ Caro Online (15x15)',
    heroDesc: 'Đấu trực tiếp với bạn bè qua liên kết hoặc luyện cờ với AI thông minh',
    freeBadge: '⚡ Miễn phí 100%',
    btnOnline: '🌐 Tạo Phòng 1:1 (Bạn Bè)',
    btnAi: '🤖 Đấu AI',
    btnLocal: '👥 Chơi Chung Máy',
    btnSound: 'Bật/Tắt âm thanh',
    btnNewGame: 'Ván Mới',
    roomTitle: 'Phòng Đấu',
    roomWait: '⏳ Đang đợi đối thủ vào phòng... Hãy copy link bên cạnh và gửi cho bạn bè!',
    roomConnected: '🟢 Đã kết nối với đối thủ! Bạn cầm quân:',
    btnCopyLink: '📋 Copy Link Phòng',
    btnCopied: '✅ Đã Copy Link!',
    btnShareZalo: '💬 Gửi Qua Zalo',
    turnYour: 'Lượt của bạn (X)',
    turnAiThinking: 'Lượt chơi: O (Máy suy nghĩ...)',
    turnPlayer: (p: string) => `Lượt chơi: ${p}`,
    turnOpponent: 'Lượt của đối thủ...',
    winMessage: (p: string) => `🎉 Người chơi ${p} chiến thắng!`,
    drawMessage: 'Hòa cờ!',
    connectingRoom: (id: string) => `Đang kết nối vào phòng ${id}...`,
    roomCreated: 'Đã tạo phòng! Hãy gửi link cho bạn bè để bắt đầu.',
    roomNotFound: 'Không tìm thấy phòng hoặc chủ phòng đã thoát.',
    peerDisconnected: 'Đối thủ đã ngắt kết nối.',
    opponentRestart: 'Đối thủ đã tạo ván mới!',
    rulesTitle: 'Tính năng thi đấu trực tuyến P2P thời gian thực',
    rulesDesc: 'Không cần đăng nhập, không cần máy chủ trung gian. Công nghệ WebRTC P2P kết nối trực tiếp hai trình duyệt với nhau, mang lại trải nghiệm đánh cờ mượt mà tức thì.',
    step1Title: '1. Bấm Tạo Phòng',
    step1Desc: 'Hệ thống tự động cấp một mã phòng ngẫu nhiên và đường link thi đấu độc quyền.',
    step2Title: '2. Gửi Link Cho Bạn Bè',
    step2Desc: 'Gửi liên kết cho đối thủ qua Zalo, Messenger hoặc bất kỳ ứng dụng nào.',
    step3Title: '3. Vào Đấu Tức Thì',
    step3Desc: 'Đối thủ mở link trên điện thoại hoặc máy tính là ván đấu tự động khởi tranh.'
  },
  ko: {
    siteTitle: '베트남 오목 (Cờ Caro)',
    siteSub: '실시간 1:1 P2P 베트남 오목 온라인',
    badgeTop: '🇻🇳 베트남 전통 5목 (P2P 실시간 1:1 대전)',
    heroTitle: '베트남 오목 온라인 (15x15)',
    heroDesc: '친구에게 링크를 보내 실시간 대국하거나 스마트 AI와 두뇌 대결을 즐기세요',
    freeBadge: '⚡ 100% 무료 게임',
    btnOnline: '🌐 1:1 온라인 방 만들기',
    btnAi: '🤖 AI 대전',
    btnLocal: '👥 한 화면 2인 대전',
    btnSound: '효과음 켜기/끄기',
    btnNewGame: '새 대국',
    roomTitle: '대국 방',
    roomWait: '⏳ 상대방의 입장을 기다리는 중입니다... 아래 링크를 복사해 친구에게 전달하세요!',
    roomConnected: '🟢 상대방이 입장했습니다! 당신의 돌:',
    btnCopyLink: '📋 대국 링크 복사',
    btnCopied: '✅ 복사 완료!',
    btnShareZalo: '💬 메신저로 공유',
    turnYour: '당신의 차례 (X)',
    turnAiThinking: '컴퓨터(O)가 생각 중입니다...',
    turnPlayer: (p: string) => `현재 차례: ${p}`,
    turnOpponent: '상대방의 차례입니다...',
    winMessage: (p: string) => `🎉 [${p}] 플레이어 승리!`,
    drawMessage: '무승부!',
    connectingRoom: (id: string) => `${id}번 방에 연결하는 중...`,
    roomCreated: '대국 방이 생성되었습니다! 초대 링크를 친구에게 보내세요.',
    roomNotFound: '방을 찾을 수 없거나 방장이 퇴장했습니다.',
    peerDisconnected: '상대방과의 연결이 끊어졌습니다.',
    opponentRestart: '상대방이 새 판을 시작했습니다!',
    rulesTitle: '서버 중계 없는 WebRTC 실시간 P2P 대전 기술',
    rulesDesc: '별도 회원가입이나 앱 설치 없이 브라우저 간 직접 연결(WebRTC P2P)로 딜레이 없는 초고속 실시간 대국을 제공합니다.',
    step1Title: '1. 온라인 방 생성',
    step1Desc: '클릭 한 번으로 고유한 1:1 대국 방 번호와 초대 링크가 즉시 발급됩니다.',
    step2Title: '2. 친구에게 링크 전송',
    step2Desc: '카카오톡, 문자, 메신저 등으로 생성된 링크를 친구에게 공유합니다.',
    step3Title: '3. 즉시 대국 시작',
    step3Desc: '상대방이 스마트폰이나 PC로 링크를 열면 즉시 대국판이 연결됩니다.'
  },
  en: {
    siteTitle: 'Caro Online (Gomoku)',
    siteSub: 'Real-time 1v1 P2P Gomoku in Browser',
    badgeTop: '🇻🇳 Vietnamese Caro (Real-time P2P 1v1)',
    heroTitle: 'Caro Online (15x15 Gomoku)',
    heroDesc: 'Play against friends via instant invite link or practice against AI',
    freeBadge: '⚡ 100% Free',
    btnOnline: '🌐 Create 1v1 Online Room',
    btnAi: '🤖 vs AI',
    btnLocal: '👥 Local 2 Players',
    btnSound: 'Toggle Sound',
    btnNewGame: 'New Game',
    roomTitle: 'Battle Room',
    roomWait: '⏳ Waiting for opponent to join... Copy and send the link to your friend!',
    roomConnected: '🟢 Opponent joined! You play as:',
    btnCopyLink: '📋 Copy Room Link',
    btnCopied: '✅ Copied!',
    btnShareZalo: '💬 Share Link',
    turnYour: 'Your turn (X)',
    turnAiThinking: 'Turn: O (AI is thinking...)',
    turnPlayer: (p: string) => `Turn: ${p}`,
    turnOpponent: 'Opponent turn...',
    winMessage: (p: string) => `🎉 Player ${p} Wins!`,
    drawMessage: 'Draw Game!',
    connectingRoom: (id: string) => `Connecting to room ${id}...`,
    roomCreated: 'Room ready! Share the link with your opponent to play.',
    roomNotFound: 'Room not found or host has left.',
    peerDisconnected: 'Opponent disconnected.',
    opponentRestart: 'Opponent requested a new game!',
    rulesTitle: 'Serverless Real-Time P2P WebRTC Matchmaking',
    rulesDesc: 'No login, no heavy servers required. WebRTC P2P technology connects both browsers directly for ultra-low latency multiplayer.',
    step1Title: '1. Create Room',
    step1Desc: 'Generates a unique room code and instant matchmaking URL.',
    step2Title: '2. Share Invite Link',
    step2Desc: 'Send the battle link to your opponent via any chat messenger.',
    step3Title: '3. Instant Play',
    step3Desc: 'Once opened on phone or PC, the game starts instantly in browser.'
  }
};
