import { writable } from 'svelte/store';

export type Lang = 'en' | 'fr' | 'de' | 'es' | 'vi' | 'ja' | 'ko';

export const currentLang = writable<Lang>('en');

export const translations = {
  en: {
    siteTitle: 'Nomad Invoice Maker',
    subBrand: 'Zero-Login A4 PDF Invoice & Receipt Generator',
    badge: '🔒 100% In-Browser · 0KB Server Upload',
    heroTitle: 'Instant Freelance Invoice & Receipt Builder',
    heroSub: 'Create clean, professional A4 invoices with multi-currency & tax support. No signup, zero server tracking, 1-click PDF download.',
    invoiceTitle: 'INVOICE',
    fromSection: 'From (Your Business)',
    toSection: 'Billed To (Client)',
    invNumber: 'Invoice #',
    issueDate: 'Issue Date',
    dueDate: 'Due Date',
    currency: 'Currency',
    descCol: 'Item Description',
    qtyCol: 'Qty',
    priceCol: 'Unit Price',
    totalCol: 'Amount',
    addItemBtn: '+ Add Item',
    subtotal: 'Subtotal',
    taxRate: 'Tax / VAT (%)',
    discount: 'Discount',
    totalDue: 'Total Due',
    paymentTerms: 'Payment Terms & Notes',
    paymentTermsPlaceholder: 'Payment due within 14 days.\nBank transfer: IBAN GB29... / BIC...\nWise: email@domain.com',
    printPdfBtn: '🖨️ Print / Save A4 PDF',
    resetBtn: 'Reset',
    sampleBtn: 'Load Sample',
    privacyNote: '🔒 All data is stored only in your local browser storage. No financial information is ever transmitted to any server.',
    faqTitle: 'Frequently Asked Questions',
    faq1Q: 'Q. How do I save this as a PDF file?',
    faq1A: 'A. Click the "Print / Save A4 PDF" button. In your browser print dialog, select "Destination: Save as PDF" with Margins set to "None" or "Default".',
    faq2Q: 'Q. Does Nomad Invoice store my invoices or client info?',
    faq2A: 'A. No. 100% of data stays strictly inside your device browser localStorage. We do not operate an invoice database.'
  },
  ko: {
    siteTitle: '노마드 인보이스 메이커',
    subBrand: '가입 없는 A4 PDF 청구서 & 영수증 생성기',
    badge: '🔒 100% 브라우저 로컬 연산 · 서버 전송 0KB',
    heroTitle: '가입 없는 1초 프리랜서 인보이스/청구서 빌더',
    heroSub: '해외 클라이언트 외주, 프리랜서 정산에 필요한 깔끔한 A4 PDF 인보이스를 즉시 제작하세요. 다국적 통화, 부가세/세율 자동 계산.',
    invoiceTitle: 'INVOICE (청구서)',
    fromSection: '발행자 (내 정보 / 사업자)',
    toSection: '수신처 (클라이언트 / 고객사)',
    invNumber: '청구서 번호',
    issueDate: '발행일',
    dueDate: '입금 마감일',
    currency: '화폐 단위',
    descCol: '품목 / 서비스 내역',
    qtyCol: '수량',
    priceCol: '단가',
    totalCol: '합계',
    addItemBtn: '+ 항목 추가',
    subtotal: '공급가액 소계',
    taxRate: '부가가치세 / 세율 (%)',
    discount: '할인 금액',
    totalDue: '최종 청구 총액',
    paymentTerms: '입금 계좌 및 결제 조건',
    paymentTermsPlaceholder: '입금 기한: 발행일로부터 14일 이내\n입금 계좌: 카카오뱅크 3333-xx-xxxxxx (예금주: 홍길동)\nWise: account@domain.com',
    printPdfBtn: '🖨️ A4 인쇄 / PDF 저장',
    resetBtn: '초기화',
    sampleBtn: '예시 불러오기',
    privacyNote: '🔒 모든 인보이스와 금액 정보는 귀하의 브라우저 로컬스토리지에만 저장되며, 외부 서버로 1바이트도 전송되지 않습니다.',
    faqTitle: '자주 묻는 질문 (FAQ)',
    faq1Q: 'Q. PDF 파일로 어떻게 저장하나요?',
    faq1A: 'A. "A4 인쇄 / PDF 저장" 버튼을 누른 후, 브라우저 인쇄 창의 대상을 "PDF로 저장"으로 선택하시면 여백 없이 완벽한 A4 PDF 문서가 생성됩니다.',
    faq2Q: 'Q. 작성한 클라이언트 정보나 계좌번호가 서버에 남나요?',
    faq2A: 'A. 일절 남지 않습니다. 100% 클라이언트 사이드 연산으로 기밀 비즈니스 정산도 안심하고 진행하실 수 있습니다.'
  },
  fr: {
    siteTitle: 'Nomad Invoice Maker',
    subBrand: 'Générateur de Factures & Reçus A4 PDF Sans Inscription',
    badge: '🔒 100% Côté Navigateur · 0 Ko Serveur',
    heroTitle: 'Générateur de Factures Freelance Instantané',
    heroSub: 'Créez des factures professionnelles A4 avec TVA et devises internationales. Zéro inscription, confidentialité totale, export PDF 1 clic.',
    invoiceTitle: 'FACTURE',
    fromSection: 'Émetteur (Vos coordonnées)',
    toSection: 'Facturé à (Client)',
    invNumber: 'N° Facture',
    issueDate: 'Date d\'émission',
    dueDate: 'Date d\'échéance',
    currency: 'Devise',
    descCol: 'Description',
    qtyCol: 'Qté',
    priceCol: 'Prix Unitaire',
    totalCol: 'Montant',
    addItemBtn: '+ Ajouter une ligne',
    subtotal: 'Sous-total HT',
    taxRate: 'TVA (%)',
    discount: 'Remise',
    totalDue: 'Total TTC',
    paymentTerms: 'Conditions de règlement & IBAN',
    paymentTermsPlaceholder: 'Paiement sous 14 jours.\nVirement bancaire : IBAN FR76...\nWise / PayPal : contact@domaine.fr',
    printPdfBtn: '🖨️ Imprimer / PDF A4',
    resetBtn: 'Réinitialiser',
    sampleBtn: 'Exemple',
    privacyNote: '🔒 Toutes les données restent stockées localement dans votre navigateur. Zéro transmission vers un serveur.',
    faqTitle: 'Foire Aux Questions',
    faq1Q: 'Q. Comment exporter en PDF ?',
    faq1A: 'A. Cliquez sur "Imprimer / PDF A4" et choisissez "Enregistrer au format PDF" dans la boîte de dialogue d\'impression.',
    faq2Q: 'Q. Mes données clients sont-elles enregistrées ?',
    faq2A: 'A. Non, tout fonctionne 100% en local dans votre navigateur sans base de données externe.'
  },
  de: {
    siteTitle: 'Nomad Invoice Maker',
    subBrand: 'Rechnungsgenerator A4 PDF Ohne Registrierung',
    badge: '🔒 100% Im Browser · 0 KB Server-Upload',
    heroTitle: 'Schneller Rechnungs- & Quittungsgenerator für Freelancer',
    heroSub: 'Erstellen Sie professionelle Rechnungen im A4-Format mit MwSt. und Währungsauswahl ohne lästige Benutzerkonten.',
    invoiceTitle: 'RECHNUNG',
    fromSection: 'Rechnungssteller (Ihre Daten)',
    toSection: 'Rechnungsempfänger (Kunde)',
    invNumber: 'Rechnungs-Nr.',
    issueDate: 'Rechnungsdatum',
    dueDate: 'Fälligkeitsdatum',
    currency: 'Währung',
    descCol: 'Beschreibung',
    qtyCol: 'Menge',
    priceCol: 'Einzelpreis',
    totalCol: 'Gesamt',
    addItemBtn: '+ Position hinzufügen',
    subtotal: 'Zwischensumme (Netto)',
    taxRate: 'Umsatzsteuer / MwSt. (%)',
    discount: 'Rabatt',
    totalDue: 'Gesamtbetrag (Brutto)',
    paymentTerms: 'Zahlungsbedingungen & Bankverbindung',
    paymentTermsPlaceholder: 'Zahlbar innerhalb von 14 Tagen.\nBankverbindung: IBAN DE89...\nWise: mail@domain.de',
    printPdfBtn: '🖨️ Drucken / Als PDF speichern',
    resetBtn: 'Zurücksetzen',
    sampleBtn: 'Beispiel laden',
    privacyNote: '🔒 Alle Daten verbleiben lokal in Ihrem Browser. Keine Serverübertragung.',
    faqTitle: 'Häufig gestellte Fragen (FAQ)',
    faq1Q: 'Q. Wie speichere ich die Rechnung als PDF?',
    faq1A: 'A. Klicken Sie auf "Drucken / Als PDF speichern" und wählen Sie als Ziel "Als PDF speichern".',
    faq2Q: 'Q. Werden Kundendaten online gespeichert?',
    faq2A: 'A. Nein, 100% vertrauliche lokale Verarbeitung in Ihrem Browser.'
  },
  es: {
    siteTitle: 'Nomad Invoice Maker',
    subBrand: 'Generador de Facturas A4 PDF Sin Registro',
    badge: '🔒 100% En Navegador · 0KB Servidor',
    heroTitle: 'Generador de Facturas para Freelancers',
    heroSub: 'Crea facturas y recibos profesionales en tamaño A4 con cálculo de IVA y múltiples divisas al instante.',
    invoiceTitle: 'FACTURA',
    fromSection: 'Emisor (Tus datos)',
    toSection: 'Cliente (Facturado a)',
    invNumber: 'N° Factura',
    issueDate: 'Fecha emisión',
    dueDate: 'Fecha vencimiento',
    currency: 'Moneda',
    descCol: 'Concepto / Descripción',
    qtyCol: 'Cant.',
    priceCol: 'Precio Unitario',
    totalCol: 'Importe',
    addItemBtn: '+ Agregar concepto',
    subtotal: 'Base Imponible',
    taxRate: 'IVA / Impuesto (%)',
    discount: 'Descuento',
    totalDue: 'Total a Pagar',
    paymentTerms: 'Datos de pago y condiciones',
    paymentTermsPlaceholder: 'Pago a 14 días.\nTransferencia: IBAN ES21...\nWise / PayPal: info@tudominio.es',
    printPdfBtn: '🖨️ Imprimir / Guardar PDF',
    resetBtn: 'Restablecer',
    sampleBtn: 'Cargar Ejemplo',
    privacyNote: '🔒 Toda la información se procesa localmente en tu navegador sin subidas a servidores externos.',
    faqTitle: 'Preguntas Frecuentes',
    faq1Q: 'Q. ¿Cómo guardar como PDF?',
    faq1A: 'A. Pulsa "Imprimir / Guardar PDF" y selecciona "Guardar como PDF" como destino de impresión.',
    faq2Q: 'Q. ¿Se envían mis facturas o clientes a algún servidor?',
    faq2A: 'A. No, todo se almacena en el almacenamiento local de tu propio navegador.'
  },
  vi: {
    siteTitle: 'Nomad Invoice Maker',
    subBrand: 'Tạo Hóa Đơn & Báo Giá A4 PDF Không Cần Đăng Ký',
    badge: '🔒 100% Trên Trình Duyệt · 0KB Máy Chủ',
    heroTitle: 'Công Cụ Tạo Hóa Đơn Cho Freelancer & Doanh Nghiệp',
    heroSub: 'Tạo hóa đơn chuyên nghiệp chuẩn khổ A4, tự động tính thuế VAT và hỗ trợ đa tiền tệ. Không cần đăng ký, bảo mật 100%.',
    invoiceTitle: 'HÓA ĐƠN / INVOICE',
    fromSection: 'Bên Phát Hành (Thông tin của bạn)',
    toSection: 'Khách Hàng (Người nhận)',
    invNumber: 'Số hóa đơn',
    issueDate: 'Ngày lập',
    dueDate: 'Hạn thanh toán',
    currency: 'Tiền tệ',
    descCol: 'Mô tả dịch vụ / Sản phẩm',
    qtyCol: 'SL',
    priceCol: 'Đơn giá',
    totalCol: 'Thành tiền',
    addItemBtn: '+ Thêm dòng',
    subtotal: 'Tạm tính',
    taxRate: 'Thuế VAT (%)',
    discount: 'Chiết khấu',
    totalDue: 'Tổng Cộng Thanh Toán',
    paymentTerms: 'Thông tin chuyển khoản & Ghi chú',
    paymentTermsPlaceholder: 'Thanh toán trong vòng 14 ngày.\nNgân hàng: Techcombank 1903... (Chủ TK: Nguyễn Văn A)\nWise / PayPal: email@domain.vn',
    printPdfBtn: '🖨️ In Khổ A4 / Lưu PDF',
    resetBtn: 'Làm lại',
    sampleBtn: 'Mẫu thử',
    privacyNote: '🔒 Toàn bộ dữ liệu chỉ lưu trên trình duyệt của bạn, tuyệt đối không gửi lên máy chủ.',
    faqTitle: 'Câu Hỏi Thường Gặp',
    faq1Q: 'Q. Làm sao để lưu file PDF?',
    faq1A: 'A. Bấm "In Khổ A4 / Lưu PDF" và chọn "Lưu dưới dạng PDF" trong hộp thoại in của trình duyệt.',
    faq2Q: 'Q. Thông tin tài chính có bị lộ không?',
    faq2A: 'A. Hoàn toàn không. Xử lý 100% trong bộ nhớ máy tính của bạn.'
  },
  ja: {
    siteTitle: 'Nomad Invoice Maker',
    subBrand: '登録不要 A4 PDF 請求書・領収書作成ツール',
    badge: '🔒 100% ブラウザ完結 · サーバー送信0KB',
    heroTitle: 'フリーランス・副業向け 即時PDF請求書ジェネレーター',
    heroSub: '海外案件やフリーランス案件のA4請求書を1クリック作成。消費税率・多通貨対応、アカウント登録一切不要。',
    invoiceTitle: '御請求書 / INVOICE',
    fromSection: '請求者情報（自社・屋号）',
    toSection: '請求先情報（クライアント）',
    invNumber: '請求書番号',
    issueDate: '請求日',
    dueDate: 'お支払期日',
    currency: '通貨',
    descCol: '品名・作業内容',
    qtyCol: '数量',
    priceCol: '単価',
    totalCol: '金額',
    addItemBtn: '+ 明細行を追加',
    subtotal: '小計 (税抜)',
    taxRate: '消費税率 (%)',
    discount: '値引き',
    totalDue: 'ご請求金額 (税込)',
    paymentTerms: 'お振込先口座・特記事項',
    paymentTermsPlaceholder: 'お振込期日: 発行日より14日以内\n振込先: 三菱UFJ銀行 ○○支店 普通 1234567\n口座名義: カ) サンプル',
    printPdfBtn: '🖨️ A4印刷 / PDF保存',
    resetBtn: 'リセット',
    sampleBtn: 'サンプル読込',
    privacyNote: '🔒 入力された請求情報はブラウザのlocalStorageのみに保存され、サーバーには一切送信されません。',
    faqTitle: 'よくある質問 (FAQ)',
    faq1Q: 'Q. PDFファイルとして保存するには？',
    faq1A: 'A. 「A4印刷 / PDF保存」を押し、印刷ダイアログの送信先で「PDFとして保存」を選択してください。',
    faq2Q: 'Q. 取引先情報や口座番号が外部に漏れる心配はありませんか？',
    faq2A: 'A. 一切ありません。すべての計算・描画はブラウザ内部のみで完結します。'
  }
};
