import { writable } from 'svelte/store';

export type PdfLang = 'ko' | 'en';

export const currentLang = writable<PdfLang>('en');

export const translations = {
  ko: {
    headerTitle: 'PDF 합치기 나누기',
    headerSub: 'SecurePDF',
    headerBadge: '100% 로컬 브라우저 연산 (서버 전송 없음)',
    metaTitle: 'PDF 합치기 나누기 - SecurePDF (서버 전송 0KB)',
    metaDesc: '개인정보 유출 걱정 없는 100% 브라우저 기반 PDF 합치기 및 나누기. 서버 전송 0KB, 내 기기 메모리에서 즉시 처리.',
    privacyBadge: '🔒 100% 로컬 프라이버시 보장 • 외부 서버 전송 0바이트',
    title: 'PDF 합치기 나누기',
    desc: '계약서, 금융 서류, 주민번호 등 민감한 서류가 외부 서버에 업로드될 걱정 없이, 내 브라우저 엔진에서 직접 초고속 연산합니다.',
    tabMerge: '📑 PDF 합치기 (Merge)',
    tabSplit: '✂️ PDF 분할/추출 (Split)',
    mergeTitle: '여러 개의 PDF 파일 합치기',
    mergeSubtitle: '파일 순서를 위아래로 변경하여 원하는 순서대로 병합할 수 있습니다.',
    clearAll: '전체 지우기',
    dropMergeTitle: '합칠 PDF 파일들을 드래그하거나 클릭하여 추가하세요',
    dropMergeSub: '여러 파일을 한 번에 선택할 수 있으며 대용량 파일도 즉시 인식됩니다',
    queueTitle: '선택된 파일 목록',
    totalPrefix: '총',
    totalPagesSuffix: '페이지',
    pagesSuffix: '페이지',
    moveUp: '위로 이동',
    moveDown: '아래로 이동',
    remove: '제거',
    mergeBtn: '하나의 PDF로 병합 다운로드',
    readingPages: 'PDF 페이지 정보를 읽는 중...',
    mergingLocal: '내 브라우저에서 PDF 페이지를 안전하게 병합하는 중...',
    generatingPdf: '병합된 PDF 파일 생성 중...',
    processingItem: '처리 중...',
    minMergeErr: '병합하려면 최소 2개 이상의 PDF 파일이 필요합니다.',
    splitTitle: 'PDF 페이지 분할 및 추출',
    splitSubtitle: '원하는 페이지 범위만 지정하여 새로운 PDF 파일로 안전하게 추출합니다.',
    dropSplitTitle: '분할할 PDF 파일을 드래그하거나 선택하세요',
    dropSplitSub: '1개 파일 선택 가능',
    changeFile: '다른 파일 선택',
    rangeLabel: '추출할 페이지 번호 또는 범위',
    rangePlaceholder: '예: 1-3, 5, 7-9',
    rangeHint: '콤마(,)와 하이픈(-)을 사용하여 유연하게 페이지를 지정할 수 있습니다 (예: 1, 3, 5-8).',
    splitBtn: '지정한 페이지만 새 PDF로 추출',
    analyzingPdf: 'PDF 페이지 구조 분석 중...',
    splittingPages: '선택한 페이지를 추출 및 분할하는 중...',
    validRangeErr: '유효한 페이지 번호를 입력해주세요 (예: 1-3, 5).',
    onlyPdfErr: 'PDF 파일만 업로드할 수 있습니다.',
    readErrPrefix: '파일을 읽는 중 오류가 발생했습니다: ',
    renderingNotice: '내 컴퓨터의 프로세서와 메모리를 사용하여 직접 렌더링 중입니다.',
    archTitle: '서버 무전송 안심 처리 원리',
    archItem1Title: '💻 로컬 CPU/RAM 연산',
    archItem1Desc: '인터넷 망을 통해 파일 바이트가 전송되지 않고 사용자의 기기 자원만으로 즉각 처리됩니다.',
    archItem2Title: '🚫 데이터 저장 0%',
    archItem2Desc: '어떠한 클라우드나 데이터베이스에도 보관되지 않으며 브라우저 탭을 닫는 즉시 메모리에서 영구 파기됩니다.',
    archItem3Title: '⚡ 무제한 용량 & 초고속',
    archItem3Desc: '서버 업로드/다운로드 대기 시간이 없어 수백 페이지 대용량 문서도 수초 이내에 병합/분할됩니다.'
  },
  en: {
    headerTitle: 'Secure PDF Merge & Split',
    headerSub: 'SecurePDF',
    headerBadge: '100% Client-Side Processing (0KB Server Upload)',
    metaTitle: 'Secure PDF Merge & Split - SecurePDF (Zero Server Upload)',
    metaDesc: 'Process confidential PDFs directly in your browser. 100% client-side merge & extract with 0 bytes uploaded to remote servers.',
    privacyBadge: '🔒 100% Client Privacy • Zero Server Uploads Guaranteed',
    title: 'Secure PDF Merge & Split',
    desc: 'Confidential agreements, IDs, and financial records never leave your device. Processed at native speed inside your browser.',
    tabMerge: '📑 Merge PDFs',
    tabSplit: '✂️ Split / Extract Pages',
    mergeTitle: 'Merge Multiple PDF Files',
    mergeSubtitle: 'Drag files or click up/down arrows to reorder before merging into a single document.',
    clearAll: 'Clear all',
    dropMergeTitle: 'Drop PDF files here, or click to browse',
    dropMergeSub: 'Select multiple documents at once. Large documents processed instantly.',
    queueTitle: 'Selected Documents',
    totalPrefix: 'Total',
    totalPagesSuffix: 'pages',
    pagesSuffix: 'pages',
    moveUp: 'Move Up',
    moveDown: 'Move Down',
    remove: 'Remove',
    mergeBtn: 'Download Merged PDF',
    readingPages: 'Reading PDF page info...',
    mergingLocal: 'Merging PDF pages locally in browser memory...',
    generatingPdf: 'Generating final PDF document...',
    processingItem: 'processing...',
    minMergeErr: 'At least 2 PDF documents are required to merge.',
    splitTitle: 'Split & Extract PDF Pages',
    splitSubtitle: 'Specify page numbers or ranges to safely extract into a clean new document.',
    dropSplitTitle: 'Drop a PDF file here, or click to select',
    dropSplitSub: '1 file supported',
    changeFile: 'Choose different file',
    rangeLabel: 'Pages or Range to Extract',
    rangePlaceholder: 'e.g. 1-3, 5, 7-9',
    rangeHint: 'Use commas and hyphens to select flexible page ranges (e.g. 1, 3, 5-8).',
    splitBtn: 'Extract Specified Pages',
    analyzingPdf: 'Analyzing PDF page structure...',
    splittingPages: 'Extracting selected pages...',
    validRangeErr: 'Please enter a valid page number or range (e.g. 1-3, 5).',
    onlyPdfErr: 'Only PDF documents (.pdf) are supported.',
    readErrPrefix: 'Error loading file: ',
    renderingNotice: 'Rendering client-side using your computer processor and memory.',
    archTitle: 'How Zero-Upload Architecture Works',
    archItem1Title: '💻 Local CPU/RAM Processing',
    archItem1Desc: 'Zero bytes transferred across external networks. All computations run inside your local JavaScript/Wasm engine.',
    archItem2Title: '🚫 Zero Data Retention',
    archItem2Desc: 'Never saved to any cloud database or server disk. Everything is wiped as soon as you close or refresh this tab.',
    archItem3Title: '⚡ Unlimited Size & Instant Speed',
    archItem3Desc: 'No upload/download queue latency. Merge or split hundreds of pages in just seconds directly on your device.'
  }
};
