import { writable } from 'svelte/store';

export type PdfLang = 'en' | 'fr' | 'de' | 'es' | 'vi' | 'ja' | 'ko';

export const currentLang = writable<PdfLang>('en');

export const translations: Record<PdfLang, {
  headerTitle: string;
  headerSub: string;
  headerBadge: string;
  metaTitle: string;
  metaDesc: string;
  privacyBadge: string;
  title: string;
  desc: string;
  tabMerge: string;
  tabSplit: string;
  mergeTitle: string;
  mergeSubtitle: string;
  clearAll: string;
  dropMergeTitle: string;
  dropMergeSub: string;
  queueTitle: string;
  totalPrefix: string;
  totalPagesSuffix: string;
  pagesSuffix: string;
  moveUp: string;
  moveDown: string;
  remove: string;
  mergeBtn: string;
  readingPages: string;
  mergingLocal: string;
  generatingPdf: string;
  processingItem: string;
  minMergeErr: string;
  splitTitle: string;
  splitSubtitle: string;
  dropSplitTitle: string;
  dropSplitSub: string;
  changeFile: string;
  rangeLabel: string;
  rangePlaceholder: string;
  rangeHint: string;
  splitBtn: string;
  analyzingPdf: string;
  splittingPages: string;
  validRangeErr: string;
  onlyPdfErr: string;
  readErrPrefix: string;
  renderingNotice: string;
  archTitle: string;
  archItem1Title: string;
  archItem1Desc: string;
  archItem2Title: string;
  archItem2Desc: string;
  archItem3Title: string;
  archItem3Desc: string;
}> = {
  en: {
    headerTitle: 'Secure PDF Merge & Split',
    headerSub: 'SecurePDF',
    headerBadge: '100% Client-Side Processing (0KB Server Upload)',
    metaTitle: 'Secure PDF Merge & Split - SecurePDF (Zero Server Upload)',
    metaDesc: 'Process confidential PDFs directly in your browser. 100% client-side merge & extract with 0 bytes uploaded to remote servers.',
    privacyBadge: '🔒 100% Client Privacy • Zero Server Uploads Guaranteed',
    title: 'Secure PDF Merge & Split',
    desc: 'Confidential agreements, IDs, and financial records never leave your device. Processed at native speed inside your browser.',
    tabMerge: '📑 Merge PDFs',
    tabSplit: '✂️ Split / Extract Pages',
    mergeTitle: 'Merge Multiple PDF Files',
    mergeSubtitle: 'Drag files or click up/down arrows to reorder before merging into a single document.',
    clearAll: 'Clear all',
    dropMergeTitle: 'Drop PDF files here, or click to browse',
    dropMergeSub: 'Select multiple documents at once. Large documents processed instantly.',
    queueTitle: 'Selected Documents',
    totalPrefix: 'Total',
    totalPagesSuffix: 'pages',
    pagesSuffix: 'pages',
    moveUp: 'Move Up',
    moveDown: 'Move Down',
    remove: 'Remove',
    mergeBtn: 'Download Merged PDF',
    readingPages: 'Reading PDF page info...',
    mergingLocal: 'Merging PDF pages locally in browser memory...',
    generatingPdf: 'Generating final PDF document...',
    processingItem: 'processing...',
    minMergeErr: 'At least 2 PDF documents are required to merge.',
    splitTitle: 'Split & Extract PDF Pages',
    splitSubtitle: 'Specify page numbers or ranges to safely extract into a clean new document.',
    dropSplitTitle: 'Drop a PDF file here, or click to select',
    dropSplitSub: '1 file supported',
    changeFile: 'Choose different file',
    rangeLabel: 'Pages or Range to Extract',
    rangePlaceholder: 'e.g. 1-3, 5, 7-9',
    rangeHint: 'Use commas and hyphens to select flexible page ranges (e.g. 1, 3, 5-8).',
    splitBtn: 'Extract Specified Pages',
    analyzingPdf: 'Analyzing PDF page structure...',
    splittingPages: 'Extracting selected pages...',
    validRangeErr: 'Please enter a valid page number or range (e.g. 1-3, 5).',
    onlyPdfErr: 'Only PDF documents (.pdf) are supported.',
    readErrPrefix: 'Error loading file: ',
    renderingNotice: 'Rendering client-side using your computer processor and memory.',
    archTitle: 'How Zero-Upload Architecture Works',
    archItem1Title: '💻 Local CPU/RAM Processing',
    archItem1Desc: 'Zero bytes transferred across external networks. All computations run inside your local JavaScript/Wasm engine.',
    archItem2Title: '🚫 Zero Data Retention',
    archItem2Desc: 'Never saved to any cloud database or server disk. Everything is wiped as soon as you close or refresh this tab.',
    archItem3Title: '⚡ Unlimited Size & Instant Speed',
    archItem3Desc: 'No upload/download queue latency. Merge or split hundreds of pages in just seconds directly on your device.'
  },
  fr: {
    headerTitle: 'Fusionner et Diviser PDF',
    headerSub: 'SecurePDF',
    headerBadge: '100% Côté Client (0KB Téléversé)',
    metaTitle: 'Fusionner et Diviser PDF - SecurePDF (Zéro Envoi Serveur)',
    metaDesc: 'Traitez vos PDF confidentiels directement dans votre navigateur. 100% local, aucun fichier envoyé sur un serveur.',
    privacyBadge: '🔒 Confidentialité Totale • Zéro Téléversement Garanti',
    title: 'Fusionner et Diviser PDF',
    desc: 'Contrats, relevés bancaires et pièces d\'identité ne quittent jamais votre ordinateur. Traitement instantané en mémoire locale.',
    tabMerge: '📑 Fusionner des PDF',
    tabSplit: '✂️ Diviser / Extraire',
    mergeTitle: 'Fusionner plusieurs fichiers PDF',
    mergeSubtitle: 'Glissez les fichiers ou réorganisez l\'ordre avant d\'assembler en un seul document.',
    clearAll: 'Tout effacer',
    dropMergeTitle: 'Glissez vos fichiers PDF ici, ou cliquez pour parcourir',
    dropMergeSub: 'Sélectionnez plusieurs documents. Traitement immédiat sans attente de téléversement.',
    queueTitle: 'Documents sélectionnés',
    totalPrefix: 'Total',
    totalPagesSuffix: 'pages',
    pagesSuffix: 'pages',
    moveUp: 'Monter',
    moveDown: 'Descendre',
    remove: 'Supprimer',
    mergeBtn: 'Télécharger le PDF fusionné',
    readingPages: 'Lecture des pages PDF...',
    mergingLocal: 'Fusion locale dans la mémoire du navigateur...',
    generatingPdf: 'Génération du PDF final...',
    processingItem: 'traitement...',
    minMergeErr: 'Au moins 2 documents PDF sont requis pour la fusion.',
    splitTitle: 'Diviser et extraire des pages',
    splitSubtitle: 'Indiquez les numéros ou plages de pages à extraire dans un nouveau document.',
    dropSplitTitle: 'Glissez un fichier PDF ici, ou cliquez pour sélectionner',
    dropSplitSub: '1 document pris en charge',
    changeFile: 'Changer de fichier',
    rangeLabel: 'Pages ou plages à extraire',
    rangePlaceholder: 'ex. 1-3, 5, 7-9',
    rangeHint: 'Utilisez des virgules et des tirets (ex. 1, 3, 5-8).',
    splitBtn: 'Extraire les pages sélectionnées',
    analyzingPdf: 'Analyse de la structure du PDF...',
    splittingPages: 'Extraction des pages en cours...',
    validRangeErr: 'Veuillez saisir une plage de pages valide (ex. 1-3, 5).',
    onlyPdfErr: 'Seuls les fichiers PDF (.pdf) sont acceptés.',
    readErrPrefix: 'Erreur lors du chargement : ',
    renderingNotice: 'Rendu local assuré par le processeur et la mémoire de votre appareil.',
    archTitle: 'Pourquoi l\'architecture zéro téléversement protège vos données',
    archItem1Title: '💻 Exécution 100% CPU/RAM Locale',
    archItem1Desc: 'Zéro octet ne transite sur internet. Tout est calculé dans le bac à sable local de votre navigateur.',
    archItem2Title: '🚫 Zéro Stockage Cloud',
    archItem2Desc: 'Aucune copie sur serveur distant. La mémoire est immédiatement purgée à la fermeture de l\'onglet.',
    archItem3Title: '⚡ Vitesse Native Sans Attente',
    archItem3Desc: 'Pas de file d\'attente réseau. Fusionnez ou divisez des centaines de pages en quelques secondes.'
  },
  de: {
    headerTitle: 'PDF Zusammenfügen & Teilen',
    headerSub: 'SecurePDF',
    headerBadge: '100% Lokale Browser-Verarbeitung (0KB Server-Upload)',
    metaTitle: 'PDF Zusammenfügen & Teilen - SecurePDF (Ohne Server-Upload)',
    metaDesc: 'Vertrauliche PDFs direkt im Browser bearbeiten. 100% clientseitig ohne Datenübertragung an externe Server.',
    privacyBadge: '🔒 100% Datenschutz • Garantiert kein Server-Upload',
    title: 'PDF Zusammenfügen & Teilen',
    desc: 'Verträge, Ausweise und Finanzdokumente verlassen niemals Ihr Gerät. Blitzschnell im lokalen Speicher verarbeitet.',
    tabMerge: '📑 PDFs Zusammenfügen',
    tabSplit: '✂️ Seiten Teilen / Extrahieren',
    mergeTitle: 'Mehrere PDF-Dateien zusammenfügen',
    mergeSubtitle: 'Dateien per Drag & Drop sortieren und zu einem Gesamtdokument verbinden.',
    clearAll: 'Alle löschen',
    dropMergeTitle: 'PDFs hierher ziehen oder zum Auswählen klicken',
    dropMergeSub: 'Wählen Sie mehrere Dokumente gleichzeitig aus. Keine Upload-Wartezeit.',
    queueTitle: 'Ausgewählte Dokumente',
    totalPrefix: 'Gesamt',
    totalPagesSuffix: 'Seiten',
    pagesSuffix: 'Seiten',
    moveUp: 'Nach oben',
    moveDown: 'Nach unten',
    remove: 'Entfernen',
    mergeBtn: 'Zusammengefügtes PDF herunterladen',
    readingPages: 'Lese PDF-Seiteninformationen...',
    mergingLocal: 'Verbinde PDF-Seiten im lokalen Browser-RAM...',
    generatingPdf: 'Erstelle finales PDF-Dokument...',
    processingItem: 'wird verarbeitet...',
    minMergeErr: 'Mindestens 2 PDF-Dateien zum Zusammenfügen erforderlich.',
    splitTitle: 'PDF-Seiten Teilen & Extrahieren',
    splitSubtitle: 'Bestimmte Seitenzahlen oder Bereiche auswählen und als neues PDF speichern.',
    dropSplitTitle: 'PDF-Datei hierher ziehen oder auswählen',
    dropSplitSub: '1 Datei unterstützt',
    changeFile: 'Andere Datei wählen',
    rangeLabel: 'Zu extrahierende Seitenzahlen / Bereiche',
    rangePlaceholder: 'z.B. 1-3, 5, 7-9',
    rangeHint: 'Nutzen Sie Kommas und Bindestriche (z.B. 1, 3, 5-8).',
    splitBtn: 'Ausgewählte Seiten extrahieren',
    analyzingPdf: 'Analysiere PDF-Struktur...',
    splittingPages: 'Extrahiere ausgewählte Seiten...',
    validRangeErr: 'Bitte gültigen Seitenbereich eingeben (z.B. 1-3, 5).',
    onlyPdfErr: 'Nur PDF-Dateien (.pdf) werden unterstützt.',
    readErrPrefix: 'Fehler beim Laden der Datei: ',
    renderingNotice: 'Lokale Ausführung auf der CPU und dem Speicher Ihres Computers.',
    archTitle: 'Vorteile der Zero-Upload-Architektur',
    archItem1Title: '💻 Lokale CPU/RAM Verarbeitung',
    archItem1Desc: 'Kein einziges Byte wird über externe Netzwerke übertragen. Vollständige Ausführung im Browser.',
    archItem2Title: '🚫 Keine Datenspeicherung',
    archItem2Desc: 'Nichts wird auf fremden Servern gespeichert. Schließen des Tabs löscht den gesamten Speicher.',
    archItem3Title: '⚡ Maximale Geschwindigkeit',
    archItem3Desc: 'Keine Netzwerk-Latenz. Verarbeiten Sie hunderte Seiten in wenigen Sekunden.'
  },
  es: {
    headerTitle: 'Unir y Dividir PDF',
    headerSub: 'SecurePDF',
    headerBadge: '100% en Navegador (0KB Subida al Servidor)',
    metaTitle: 'Unir y Dividir PDF - SecurePDF (Sin Subir Archivos)',
    metaDesc: 'Procese archivos PDF confidenciales directamente en su navegador. 100% local sin transferir datos a servidores.',
    privacyBadge: '🔒 Privacidad Absoluta • Cero Carga al Servidor',
    title: 'Unir y Dividir PDF',
    desc: 'Contratos, identificaciones y documentos bancarios nunca salen de su dispositivo. Procesamiento local instantáneo.',
    tabMerge: '📑 Unir PDFs',
    tabSplit: '✂️ Dividir / Extraer',
    mergeTitle: 'Unir múltiples archivos PDF',
    mergeSubtitle: 'Ordene los archivos arrastrando antes de fusionarlos en un único documento.',
    clearAll: 'Borrar todo',
    dropMergeTitle: 'Arrastre archivos PDF aquí o haga clic para buscar',
    dropMergeSub: 'Seleccione varios documentos a la vez. Sin tiempos de espera de subida.',
    queueTitle: 'Documentos seleccionados',
    totalPrefix: 'Total',
    totalPagesSuffix: 'páginas',
    pagesSuffix: 'páginas',
    moveUp: 'Subir',
    moveDown: 'Bajar',
    remove: 'Eliminar',
    mergeBtn: 'Descargar PDF Unido',
    readingPages: 'Leyendo páginas del PDF...',
    mergingLocal: 'Uniendo páginas localmente en la memoria...',
    generatingPdf: 'Generando documento PDF final...',
    processingItem: 'procesando...',
    minMergeErr: 'Se requieren al menos 2 archivos PDF para unir.',
    splitTitle: 'Dividir y Extraer Páginas PDF',
    splitSubtitle: 'Indique los números o rangos de páginas para extraer a un nuevo documento.',
    dropSplitTitle: 'Arrastre un archivo PDF aquí o selecciónelo',
    dropSplitSub: '1 archivo compatible',
    changeFile: 'Elegir otro archivo',
    rangeLabel: 'Páginas o rangos a extraer',
    rangePlaceholder: 'ej. 1-3, 5, 7-9',
    rangeHint: 'Use comas y guiones (ej. 1, 3, 5-8).',
    splitBtn: 'Extraer páginas especificadas',
    analyzingPdf: 'Analizando estructura del PDF...',
    splittingPages: 'Extrayendo páginas seleccionadas...',
    validRangeErr: 'Ingrese un rango de páginas válido (ej. 1-3, 5).',
    onlyPdfErr: 'Solo se admiten documentos PDF (.pdf).',
    readErrPrefix: 'Error al abrir archivo: ',
    renderingNotice: 'Procesamiento en memoria usando la CPU y RAM de su dispositivo.',
    archTitle: 'Seguridad de la Arquitectura Cero Subida',
    archItem1Title: '💻 Procesamiento 100% en CPU/RAM Local',
    archItem1Desc: 'Cero bytes enviados a través de redes externas. Todo corre dentro de su navegador.',
    archItem2Title: '🚫 Cero Retención de Datos',
    archItem2Desc: 'Nunca se guarda en ningún servidor o nube. Se borra instantáneamente al cerrar la pestaña.',
    archItem3Title: '⚡ Velocidad Máxima Sin Esperas',
    archItem3Desc: 'Sin colas ni límites de ancho de banda. Una o divida cientos de páginas en segundos.'
  },
  vi: {
    headerTitle: 'Nối & Ghép, Cắt File PDF',
    headerSub: 'SecurePDF',
    headerBadge: '100% Xử Lý Trực Tiếp Trong Trình Duyệt (0KB Upload)',
    metaTitle: 'Nối và Cắt File PDF An Toàn - SecurePDF (Không Tải Lên Server)',
    metaDesc: 'Ghép và tách trang PDF trực tiếp trên trình duyệt. Bảo mật tuyệt đối, không tải dữ liệu lên server ngoài.',
    privacyBadge: '🔒 Bảo Mật Tuyệt Đối • Không Tải Dữ Liệu Lên Server',
    title: 'Nối & Cắt Trang PDF An Toàn',
    desc: 'Hợp đồng, căn cước và tài liệu mật không bao giờ rời khỏi thiết bị của bạn. Xử lý tức thì trong RAM trình duyệt.',
    tabMerge: '📑 Nối File PDF',
    tabSplit: '✂️ Tách / Trích Xuất Trang',
    mergeTitle: 'Ghép Nhiều File PDF Lại Thành Một',
    mergeSubtitle: 'Kéo thả hoặc nhấn mũi tên lên/xuống để sắp xếp thứ tự trước khi gộp file.',
    clearAll: 'Xóa tất cả',
    dropMergeTitle: 'Kéo thả các file PDF vào đây hoặc nhấn để chọn',
    dropMergeSub: 'Có thể chọn nhiều file cùng lúc. Xử lý nhanh chóng không cần chờ tải lên mạng.',
    queueTitle: 'Danh Sách File Đã Chọn',
    totalPrefix: 'Tổng cộng',
    totalPagesSuffix: 'trang',
    pagesSuffix: 'trang',
    moveUp: 'Di chuyển lên',
    moveDown: 'Di chuyển xuống',
    remove: 'Xóa',
    mergeBtn: 'Tải Về File PDF Đã Ghép',
    readingPages: 'Đang đọc thông tin trang PDF...',
    mergingLocal: 'Đang ghép các trang trực tiếp trong bộ nhớ máy...',
    generatingPdf: 'Đang tạo file PDF hoàn chỉnh...',
    processingItem: 'đang xử lý...',
    minMergeErr: 'Cần ít nhất 2 file PDF để tiến hành nối file.',
    splitTitle: 'Tách & Trích Xuất Trang PDF',
    splitSubtitle: 'Nhập số trang hoặc khoảng trang cần lấy để tạo file PDF mới.',
    dropSplitTitle: 'Kéo thả 1 file PDF vào đây hoặc nhấn để chọn',
    dropSplitSub: 'Hỗ trợ 1 file',
    changeFile: 'Chọn file khác',
    rangeLabel: 'Trang hoặc khoảng trang cần trích xuất',
    rangePlaceholder: 'ví dụ: 1-3, 5, 7-9',
    rangeHint: 'Dùng dấu phẩy và dấu gạch nối (ví dụ: 1, 3, 5-8).',
    splitBtn: 'Trích Xuất Trang Đã Chọn',
    analyzingPdf: 'Đang phân tích cấu trúc PDF...',
    splittingPages: 'Đang tách trang...',
    validRangeErr: 'Vui lòng nhập số trang hợp lệ (ví dụ: 1-3, 5).',
    onlyPdfErr: 'Chỉ chấp nhận file định dạng PDF (.pdf).',
    readErrPrefix: 'Lỗi khi đọc file: ',
    renderingNotice: 'Đang xử lý trực tiếp bằng CPU và bộ nhớ máy tính của bạn.',
    archTitle: 'Nguyên Lý Hoạt Động Bảo Mật 100% Của Chúng Tôi',
    archItem1Title: '💻 Tính Toán Bằng CPU/RAM Cục Bộ',
    archItem1Desc: 'Không có bất kỳ byte dữ liệu nào bị gửi qua internet. Xử lý hoàn toàn trong máy bạn.',
    archItem2Title: '🚫 Không Lưu Trữ Dữ Liệu',
    archItem2Desc: 'Không lưu trên bất kỳ máy chủ nào. Đóng tab trình duyệt là toàn bộ dữ liệu biến mất ngay lập tức.',
    archItem3Title: '⚡ Dung Lượng Không Giới Hạn & Tốc Độ Cực Nhanh',
    archItem3Desc: 'Không phải đợi tải lên hay tải xuống. Ghép hoặc tách hàng trăm trang chỉ trong vài giây.'
  },
  ja: {
    headerTitle: '安全なPDF結合・分割ツール',
    headerSub: 'SecurePDF',
    headerBadge: '100% ブラウザ内ローカル処理 (サーバー送信0KB)',
    metaTitle: '安全なPDF結合・分割ツール - SecurePDF (サーバー送信ゼロ)',
    metaDesc: '機密書類や個人情報をサーバーに一切送信せず、ブラウザ内ローカルメモリで安全にPDFを結合・ページ分割します。',
    privacyBadge: '🔒 完全ローカルプライバシー保証 • 外部送信ゼロ',
    title: '安全なPDF結合・分割ツール',
    desc: '契約書や身分証、金融書類などの重要ファイルが外部サーバーにアップロードされる心配なく、お使いの端末内で高速処理します。',
    tabMerge: '📑 PDF結合 (Merge)',
    tabSplit: '✂️ ページ抽出・分割 (Split)',
    mergeTitle: '複数のPDFファイルを1つに結合',
    mergeSubtitle: 'ファイルをドラッグまたは上下移動して順番を調整し、1つのPDFにまとめます。',
    clearAll: 'すべて削除',
    dropMergeTitle: 'ここにPDFファイルをドラッグ＆ドロップ、またはクリックして選択',
    dropMergeSub: '複数ファイルを同時に選択可能。大容量ファイルも即座に認識されます。',
    queueTitle: '選択されたファイル一覧',
    totalPrefix: '合計',
    totalPagesSuffix: 'ページ',
    pagesSuffix: 'ページ',
    moveUp: '上へ',
    moveDown: '下へ',
    remove: '削除',
    mergeBtn: '結合したPDFをダウンロード',
    readingPages: 'PDFページ情報を読み込み中...',
    mergingLocal: 'ブラウザメモリ内で安全に結合処理中...',
    generatingPdf: '結合PDFファイルを生成中...',
    processingItem: '処理中...',
    minMergeErr: '結合には最低2つ以上のPDFファイルが必要です。',
    splitTitle: 'PDFページの分割・抽出',
    splitSubtitle: '抽出したいページ番号や範囲を指定して、新しいPDFとして安全に保存します。',
    dropSplitTitle: '分割するPDFファイルをドラッグ、または選択してください',
    dropSplitSub: '1ファイル対応',
    changeFile: '別のファイルを選択',
    rangeLabel: '抽出するページ番号または範囲',
    rangePlaceholder: '例: 1-3, 5, 7-9',
    rangeHint: 'カンマ(,)とハイフン(-)を使用して柔軟にページを指定できます (例: 1, 3, 5-8)。',
    splitBtn: '指定したページを抽出してダウンロード',
    analyzingPdf: 'PDF構造を解析中...',
    splittingPages: '選択ページを抽出・分割中...',
    validRangeErr: '有効なページ番号または範囲を入力してください (例: 1-3, 5)。',
    onlyPdfErr: 'PDFファイル(.pdf)のみアップロード可能です。',
    readErrPrefix: 'ファイル読み込みエラー: ',
    renderingNotice: 'お使いの端末のCPUとメモリを使ってローカルで高速レンダリングしています。',
    archTitle: 'サーバー無送信・安心処理の仕組み',
    archItem1Title: '💻 端末のCPU/メモリで直接計算',
    archItem1Desc: 'インターネット経由でファイルが送信されることは一切なく、お使いの端末内だけで完結します。',
    archItem2Title: '🚫 データ保存 0%',
    archItem2Desc: '外部クラウドやサーバーに保管されることはなく、ブラウザを閉じるとメモリから即時破棄されます。',
    archItem3Title: '⚡ 容量無制限＆超高速',
    archItem3Desc: 'サーバー送受信の待ち時間がないため、数百ページの大容量PDFもわずか数秒で結合・分割できます。'
  },
  ko: {
    headerTitle: 'PDF 합치기 나누기',
    headerSub: 'SecurePDF',
    headerBadge: '100% 로컬 브라우저 연산 (서버 전송 없음)',
    metaTitle: 'PDF 합치기 나누기 - SecurePDF (서버 전송 0KB)',
    metaDesc: '개인정보 유출 걱정 없는 100% 브라우저 기반 PDF 합치기 및 나누기. 서버 전송 0KB, 내 기기 메모리에서 즉시 처리.',
    privacyBadge: '🔒 100% 로컬 프라이버시 보장 • 외부 서버 전송 0바이트',
    title: 'PDF 합치기 나누기',
    desc: '계약서, 금융 서류, 주민번호 등 민감한 서류가 외부 서버에 업로드될 걱정 없이, 내 브라우저 엔진에서 직접 초고속 연산합니다.',
    tabMerge: '📑 PDF 합치기 (Merge)',
    tabSplit: '✂️ PDF 분할/추출 (Split)',
    mergeTitle: '여러 개의 PDF 파일 합치기',
    mergeSubtitle: '파일 순서를 위아래로 변경하여 원하는 순서대로 병합할 수 있습니다.',
    clearAll: '전체 지우기',
    dropMergeTitle: '합칠 PDF 파일들을 드래그하거나 클릭하여 추가하세요',
    dropMergeSub: '여러 파일을 한 번에 선택할 수 있으며 대용량 파일도 즉시 인식됩니다',
    queueTitle: '선택된 파일 목록',
    totalPrefix: '총',
    totalPagesSuffix: '페이지',
    pagesSuffix: '페이지',
    moveUp: '위로 이동',
    moveDown: '아래로 이동',
    remove: '제거',
    mergeBtn: '하나의 PDF로 병합 다운로드',
    readingPages: 'PDF 페이지 정보를 읽는 중...',
    mergingLocal: '내 브라우저에서 PDF 페이지를 안전하게 병합하는 중...',
    generatingPdf: '병합된 PDF 파일 생성 중...',
    processingItem: '처리 중...',
    minMergeErr: '병합하려면 최소 2개 이상의 PDF 파일이 필요합니다.',
    splitTitle: 'PDF 페이지 분할 및 추출',
    splitSubtitle: '원하는 페이지 범위만 지정하여 새로운 PDF 파일로 안전하게 추출합니다.',
    dropSplitTitle: '분할할 PDF 파일을 드래그하거나 선택하세요',
    dropSplitSub: '1개 파일 선택 가능',
    changeFile: '다른 파일 선택',
    rangeLabel: '추출할 페이지 번호 또는 범위',
    rangePlaceholder: '예: 1-3, 5, 7-9',
    rangeHint: '콤마(,)와 하이픈(-)을 사용하여 유연하게 페이지를 지정할 수 있습니다 (예: 1, 3, 5-8).',
    splitBtn: '지정한 페이지만 새 PDF로 추출',
    analyzingPdf: 'PDF 페이지 구조 분석 중...',
    splittingPages: '선택한 페이지를 추출 및 분할하는 중...',
    validRangeErr: '유효한 페이지 번호를 입력해주세요 (예: 1-3, 5).',
    onlyPdfErr: 'PDF 파일만 업로드할 수 있습니다.',
    readErrPrefix: '파일을 읽는 중 오류가 발생했습니다: ',
    renderingNotice: '내 컴퓨터의 프로세서와 메모리를 사용하여 직접 렌더링 중입니다.',
    archTitle: '서버 무전송 안심 처리 원리',
    archItem1Title: '💻 로컬 CPU/RAM 연산',
    archItem1Desc: '인터넷 망을 통해 파일 바이트가 전송되지 않고 사용자의 기기 자원만으로 즉각 처리됩니다.',
    archItem2Title: '🚫 데이터 저장 0%',
    archItem2Desc: '어떠한 클라우드나 데이터베이스에도 보관되지 않으며 브라우저 탭을 닫는 즉시 메모리에서 영구 파기됩니다.',
    archItem3Title: '⚡ 무제한 용량 & 초고속',
    archItem3Desc: '서버 업로드/다운로드 대기 시간이 없어 수백 페이지 대용량 문서도 수초 이내에 병합/분할됩니다.'
  }
};
