import { writable } from 'svelte/store';

export type TimeSyncLang = 'en' | 'fr' | 'de' | 'es' | 'ko';

export const currentLang = writable<TimeSyncLang>('en');

export const translations = {
  en: {
    siteTitle: 'Nomad TimeSync',
    badge: '100% Client-Side • 0KB Server Upload',
    heroTitle: 'Global Timezone & Golden Meeting Hours Planner',
    heroSub: 'Instant overlap finder for digital nomads, distributed teams & expats. Coordinate cross-border meetings across Paris, New York, San Francisco, London & Asia with zero server tracking.',
    privacyBadge: '🔒 All calculations computed in-memory in your browser. No calendar or time queries are sent to any server.',
    selectedCities: 'Active Comparison Cities',
    addCityBtn: '+ Add City',
    referenceCity: 'Reference City (Drag slider or click an hour to sync all clocks)',
    goldenHoursTitle: '🌟 Overlap Golden Hours (Overlap Working Window)',
    goldenHoursDesc: 'Hours where all selected locations are within reasonable working/waking hours (08:00 – 19:00 local time).',
    noGoldenHours: 'No complete overlap found between current cities. Try checking flexible morning/evening slots below.',
    goldenSlotFound: 'Perfect overlapping hours found:',
    copyScheduleBtn: '📋 Copy Meeting Summary',
    downloadIcsBtn: '📅 Export .ICS Calendar Event',
    copiedText: 'Copied to clipboard!',
    legendWork: 'Working Hours (09-18)',
    legendFlex: 'Flexible / Early / Late (07-09, 18-22)',
    legendSleep: 'Night / Sleep (22-07)',
    faqTitle: 'Frequently Asked Questions',
    q1: 'Q. Does Nomad TimeSync handle Daylight Saving Time (DST)?',
    a1: 'A. Yes! All time conversions use the browser standard Intl.DateTimeFormat API with official IANA Timezone databases, automatically adapting to summer/winter time transitions.',
    q2: 'Q. Are my meeting schedules or location preferences tracked?',
    a2: 'A. Never. 100% of calculations execute locally in your client device memory with zero server calls.'
  },
  fr: {
    siteTitle: 'Nomad TimeSync',
    badge: '100% Côté Client • Zéro Téléversement Serveur',
    heroTitle: 'Planificateur de Fuseaux Horaires & Heures Dorées',
    heroSub: 'Trouvez instantanément les créneaux communs pour nomades digitaux, freelances et équipes à distance entre Paris, New York, San Francisco, Londres et l\'Asie.',
    privacyBadge: '🔒 Calculs 100% locaux dans votre navigateur. Aucune donnée n\'est transmise à un serveur.',
    selectedCities: 'Villes Comparées',
    addCityBtn: '+ Ajouter une Ville',
    referenceCity: 'Ville de Référence (Glissez le curseur pour synchroniser)',
    goldenHoursTitle: '🌟 Créneaux Dorés Communs (Golden Working Hours)',
    goldenHoursDesc: 'Plages horaires où toutes les villes sélectionnées sont en journée de travail ou éveillées (08h00 – 19h00 heure locale).',
    noGoldenHours: 'Aucun créneau parfait trouvé. Consultez les créneaux flexibles ci-dessous.',
    goldenSlotFound: 'Créneaux parfaits identifiés :',
    copyScheduleBtn: '📋 Copier le Récapitulatif',
    downloadIcsBtn: '📅 Exporter l\'Événement .ICS',
    copiedText: 'Copié dans le presse-papiers !',
    legendWork: 'Heures de Travail (09h-18h)',
    legendFlex: 'Heures Flexibles (07h-09h, 18h-22h)',
    legendSleep: 'Nuit / Sommeil (22h-07h)',
    faqTitle: 'Foire Aux Questions',
    q1: 'Q. Le fuseau horaire prend-il en compte l\'heure d\'été (DST) ?',
    a1: 'A. Oui. Toutes les conversions exploitent l\'API native Intl de votre navigateur basée sur la base de données officielle IANA, s\'adaptant automatiquement à l\'heure d\'été.',
    q2: 'Q. Mes choix de villes ou horaires sont-ils enregistrés ?',
    a2: 'A. Absolument pas. Tout fonctionne exclusivement dans la mémoire vive de votre navigateur sans aucun envoi vers un serveur.'
  },
  de: {
    siteTitle: 'Nomad TimeSync',
    badge: '100% Client-Side • 0KB Server-Upload',
    heroTitle: 'Weltweiter Zeitzonen- & Meeting-Planer',
    heroSub: 'Perfekte Arbeitszeit-Überschneidungen für digitale Nomaden und verteilte Teams zwischen Berlin, Paris, New York und Asien.',
    privacyBadge: '🔒 Alle Berechnungen laufen lokal im Browser ab. Keine Serverübertragung.',
    selectedCities: 'Verglichene Städte',
    addCityBtn: '+ Stadt Hinzufügen',
    referenceCity: 'Referenzstadt (Schieberegler bewegen zum Synchronisieren)',
    goldenHoursTitle: '🌟 Optimale Überschneidungszeiten (Golden Hours)',
    goldenHoursDesc: 'Stunden, in denen alle ausgewählten Standorte innerhalb normaler Arbeits- und Wachzeiten (08:00 – 19:00 Uhr) liegen.',
    noGoldenHours: 'Keine vollständige Überschneidung gefunden.',
    goldenSlotFound: 'Optimale gemeinsame Stunden gefunden:',
    copyScheduleBtn: '📋 Meeting-Zeiten Kopieren',
    downloadIcsBtn: '📅 .ICS Kalenderdatei Herunterladen',
    copiedText: 'In die Zwischenablage kopiert!',
    legendWork: 'Arbeitszeit (09-18 Uhr)',
    legendFlex: 'Flexibel (07-09, 18-22 Uhr)',
    legendSleep: 'Nachtruhe (22-07 Uhr)',
    faqTitle: 'Häufig gestellte Fragen (FAQ)',
    q1: 'Q. Werden Sommerzeit und Winterzeit automatisch beachtet?',
    a1: 'A. Ja. Die offizielle IANA-Zeitzonendatenbank Ihres Browsers passt Sommer- und Winterzeit automatisch an.',
    q2: 'Q. Werden meine Konferenzzeiten auf einem Server gespeichert?',
    a2: 'A. Nein, 100% lokaler Datenschutz ohne externe Datenspeicherung.'
  },
  es: {
    siteTitle: 'Nomad TimeSync',
    badge: '100% Lado del Cliente • 0KB al Servidor',
    heroTitle: 'Planificador de Zonas Horarias y Horas Doradas',
    heroSub: 'Encuentra al instante el horario común para reuniones de equipos remotos y nómadas digitales entre Madrid, París, Nueva York, América Latina y Asia.',
    privacyBadge: '🔒 Cálculos 100% locales en la memoria de tu navegador.',
    selectedCities: 'Ciudades Comparadas',
    addCityBtn: '+ Añadir Ciudad',
    referenceCity: 'Ciudad de Referencia (Desliza para sincronizar)',
    goldenHoursTitle: '🌟 Horas Doradas de Coincidencia (Golden Hours)',
    goldenHoursDesc: 'Horarios donde todas las ciudades seleccionadas están en horario laboral o despiertas (08:00 – 19:00 hora local).',
    noGoldenHours: 'No hay coincidencia completa encontrada.',
    goldenSlotFound: 'Horas ideales coincidentes encontradas:',
    copyScheduleBtn: '📋 Copiar Resumen de Reunión',
    downloadIcsBtn: '📅 Exportar Evento .ICS',
    copiedText: '¡Copiado al portapapeles!',
    legendWork: 'Horas de Trabajo (09-18)',
    legendFlex: 'Horario Flexible (07-09, 18-22)',
    legendSleep: 'Noche / Descanso (22-07)',
    faqTitle: 'Preguntas Frecuentes',
    q1: 'Q. ¿Incluye el cambio de hora de verano (DST)?',
    a1: 'A. Sí, utiliza la base de datos oficial IANA del navegador que gestiona el horario de verano automáticamente.',
    q2: 'Q. ¿Se transmiten mis datos?',
    a2: 'A. En absoluto. Todo se procesa 100% en la memoria de tu dispositivo.'
  },
  ko: {
    siteTitle: '노마드 타임싱크 (Nomad TimeSync)',
    badge: '🔒 100% 브라우저 메모리 연산 • 서버 전송 0KB',
    heroTitle: '글로벌 시차 조율 & 골든 워킹 아워 플래너',
    heroSub: '파리, 뉴욕, 샌프란시스코, 런던, 서울 등 전 세계 디지털 노마드 및 원격 팀을 위한 1초 시차 대조 및 공통 회의 가능 시간(Golden Hours) 계산기.',
    privacyBadge: '🔒 모든 시차 및 회의 시간 계산은 브라우저 내에서 즉각 처리되며 서버로 어떤 정보도 전송되지 않습니다.',
    selectedCities: '비교 중인 도시 목록',
    addCityBtn: '+ 도시 추가',
    referenceCity: '기준 도시 (슬라이더를 드래그하거나 특정 시간을 클릭하여 동기화)',
    goldenHoursTitle: '🌟 공통 골든 워킹 아워 (Overlap Golden Hours)',
    goldenHoursDesc: '선택된 모든 도시가 현지 기준 일과/활동 가능 시간(08:00 – 19:00)에 겹치는 최적의 회의 시간대입니다.',
    noGoldenHours: '현재 도시들 간에 완벽히 겹치는 일과 시간이 없습니다. 이른 아침/늦은 저녁 유연 시간대를 확인해보세요.',
    goldenSlotFound: '발견된 최적의 공통 회의 시간:',
    copyScheduleBtn: '📋 회의 시간 요약 복사',
    downloadIcsBtn: '📅 .ICS 캘린더 일정 다운로드',
    copiedText: '클립보드에 복사되었습니다!',
    legendWork: '정규 근무 시간 (09~18시)',
    legendFlex: '유연/활동 시간 (07~09, 18~22시)',
    legendSleep: '심야/수면 시간 (22~07시)',
    faqTitle: '자주 묻는 질문 (FAQ)',
    q1: 'Q. 서머타임(Daylight Saving Time)이 자동으로 반영되나요?',
    a1: 'A. 네! 브라우저 표준 IANA 타임존 데이터베이스(Intl API)를 직접 사용하여 유럽/북미의 서머타임 변동을 1초의 오차 없이 자동 계산합니다.',
    q2: 'Q. 회의 일정이나 검색한 도시 정보가 서버에 남나요?',
    a2: 'A. 일절 남지 않습니다. 100% 기기 로컬 메모리에서만 동작하므로 기밀 비즈니스 회의 조율도 안심하고 진행하실 수 있습니다.'
  }
};
