import { writable } from 'svelte/store';

export type Lang = 'en' | 'fr' | 'de' | 'es' | 'vi' | 'ja' | 'ko';

export const currentLang = writable<Lang>('en');

export const translations: Record<Lang, {
  siteTitle: string;
  badge: string;
  heroTitle: string;
  heroSub: string;
  privacyBadge: string;
  addTrip: string;
  entryDate: string;
  exitDate: string;
  country: string;
  note: string;
  addBtn: string;
  loadSample: string;
  clearAll: string;
  myTrips: string;
  noTrips: string;
  duration: string;
  days: string;
  delete: string;
  simTitle: string;
  simSub: string;
  refDateLabel: string;
  statusToday: string;
  usedDays: string;
  remainingDays: string;
  overstayAlert: string;
  maxContinuousStay: string;
  latestExit: string;
  completeReset: string;
  downloadIcs: string;
  timelineTitle: string;
  timelineSub: string;
  inSchengen: string;
  outSchengen: string;
  faqTitle: string;
  q1: string;
  a1: string;
  q2: string;
  a2: string;
  q3: string;
  a3: string;
}> = {
  en: {
    siteTitle: 'Schengen 90/180 Tracker',
    badge: '100% Client-Side • 0KB Server Upload',
    heroTitle: 'Schengen 90/180 Day Rollover Tracker',
    heroSub: 'Accurate rolling window calculator for non-EU travelers, digital nomads & tourists. Calculate remaining days, rollover simulations, and departure deadlines with zero server tracking.',
    privacyBadge: '🔒 All trip data saved locally in your browser (LocalStorage). Never uploaded to any server.',
    addTrip: 'Add New Trip to Schengen Area',
    entryDate: 'Entry Date',
    exitDate: 'Exit Date',
    country: 'Country (Optional)',
    note: 'Note / Purpose (Optional)',
    addBtn: '+ Add Trip',
    loadSample: 'Load Sample Trips',
    clearAll: 'Clear All',
    myTrips: 'Recorded Trips History',
    noTrips: 'No trips added yet. Add your travel dates above or load a sample scenario.',
    duration: 'Duration',
    days: 'days',
    delete: 'Delete',
    simTitle: 'Stay Status & Rollover Simulation',
    simSub: 'Simulate legal stay compliance on any chosen reference date within the 180-day rolling window.',
    refDateLabel: 'Simulation Reference Date',
    statusToday: 'Status on Reference Date',
    usedDays: 'Days Used (out of 90)',
    remainingDays: 'Days Remaining (Legal Stay)',
    overstayAlert: '⚠️ Overstay Risk Detected! You exceed the 90-day allowance.',
    maxContinuousStay: 'Maximum Continuous Stay Allowed',
    latestExit: 'Latest Legal Exit Date',
    completeReset: 'Complete 90-Day Reset (if outside)',
    downloadIcs: '📅 Download Departure Deadlines (.ics Calendar)',
    timelineTitle: '180-Day Rolling Timeline Breakdown',
    timelineSub: 'Day-by-day visual overview of your Schengen presence vs absence.',
    inSchengen: 'In Schengen',
    outSchengen: 'Outside Schengen',
    faqTitle: 'Frequently Asked Questions (FAQ)',
    q1: 'How does the Schengen 90/180 rule actually work?',
    a1: 'Non-EU citizens can stay up to 90 days within ANY 180-day window. The 180-day period rolls continuously backwards from each day of your stay, not from your first entry.',
    q2: 'Do entry and exit days count as full days?',
    a2: 'Yes. Even if you arrive at 23:59 or depart at 00:01, both the entry date and exit date count as full 1-day stays in the calculation.',
    q3: 'Is my travel data transmitted or tracked?',
    a3: 'Zero bytes leave your computer. All calculations run client-side using JavaScript, and data is kept solely in your browser LocalStorage.'
  },
  fr: {
    siteTitle: 'Calculateur Règle 90/180 Schengen',
    badge: '100% Côté Client • 0KB Téléversement Serveur',
    heroTitle: 'Calculateur de Séjour Règle 90/180 Jours Schengen',
    heroSub: 'Calculateur glissant précis pour voyageurs non-UE, nomades digitaux et touristes. Calculez les jours restants et les dates limites de départ avec zéro suivi serveur.',
    privacyBadge: '🔒 Toutes vos données de voyage restent stockées localement dans votre navigateur (LocalStorage). Zéro fuite serveur.',
    addTrip: 'Ajouter un Séjour dans l\'Espace Schengen',
    entryDate: 'Date d\'entrée',
    exitDate: 'Date de sortie',
    country: 'Pays (Facultatif)',
    note: 'Remarque / Motif (Facultatif)',
    addBtn: '+ Ajouter le séjour',
    loadSample: 'Charger un exemple',
    clearAll: 'Tout effacer',
    myTrips: 'Historique de mes séjours',
    noTrips: 'Aucun séjour enregistré. Ajoutez vos dates ci-dessus ou chargez un exemple.',
    duration: 'Durée',
    days: 'jours',
    delete: 'Supprimer',
    simTitle: 'Simulation de Statut & Jours Restants',
    simSub: 'Vérifiez votre conformité à une date de référence choisie sur la fenêtre glissante de 180 jours.',
    refDateLabel: 'Date de référence pour le calcul',
    statusToday: 'Statut à la date choisie',
    usedDays: 'Jours consommés (sur 90)',
    remainingDays: 'Jours restants autorisés',
    overstayAlert: '⚠️ Dépassement détecté ! Vous dépassez le quota autorisé de 90 jours.',
    maxContinuousStay: 'Séjour continu maximum possible',
    latestExit: 'Date limite de sortie recommandée',
    completeReset: 'Remise à zéro complète du quota 90j',
    downloadIcs: '📅 Exporter les rappels de départ (.ICS)',
    timelineTitle: 'Visualisation Chronologique (Fenêtre 180 Jours)',
    timelineSub: 'Aperçu jour par jour de vos périodes de présence et d\'absence.',
    inSchengen: 'Dans Schengen',
    outSchengen: 'Hors Schengen',
    faqTitle: 'Foire Aux Questions (FAQ)',
    q1: 'Comment fonctionne exactement la règle des 90/180 jours de l\'espace Schengen ?',
    a1: 'Tout ressortissant non-UE exempté de visa court séjour peut séjourner au maximum 90 jours sur toute période glissante de 180 jours. Chaque jour passé dans Schengen est vérifié par rapport aux 179 jours précédents.',
    q2: 'Les dates d\'entrée et de sortie comptent-elles comme des journées entières ?',
    a2: 'Oui. Le jour d\'arrivée et le jour de départ comptent chacun pour un jour complet dans le quota des 90 jours.',
    q3: 'Mes données de passeport ou de dates de voyage sont-elles envoyées à un serveur ?',
    a3: 'Non, absolument aucun octet n\'est envoyé sur un serveur. Tout est calculé dans votre navigateur.'
  },
  de: {
    siteTitle: 'Schengen 90/180 Tage Rechner',
    badge: '100% Client-Side • 0KB Server-Upload',
    heroTitle: 'Schengen 90/180 Tage Rechner & Planer',
    heroSub: 'Präziser Rechner des rollenden 180-Tage-Fensters für Touristen, digitale Nomaden und Expats. Berechnen Sie verbleibende Tage und Ausreisefristen ohne Server-Tracking.',
    privacyBadge: '🔒 Reisedaten werden ausschließlich lokal im Browser gespeichert (LocalStorage).',
    addTrip: 'Neue Reise in den Schengen-Raum hinzufügen',
    entryDate: 'Einreisedatum',
    exitDate: 'Ausreisedatum',
    country: 'Land (Optional)',
    note: 'Notiz / Zweck (Optional)',
    addBtn: '+ Reise hinzufügen',
    loadSample: 'Beispieldaten laden',
    clearAll: 'Alles löschen',
    myTrips: 'Gespeicherte Reisen',
    noTrips: 'Noch keine Reisen erfasst. Fügen Sie Reisedaten hinzu oder nutzen Sie Beispieldaten.',
    duration: 'Dauer',
    days: 'Tage',
    delete: 'Löschen',
    simTitle: 'Aufenthalts-Status & Simulation',
    simSub: 'Prüfen Sie den legalen Status an einem beliebigen Stichtag im 180-Tage-Fenster.',
    refDateLabel: 'Stichtag zur Berechnung',
    statusToday: 'Status am Stichtag',
    usedDays: 'Verbrauchte Tage (von 90)',
    remainingDays: 'Verbleibende Aufenthaltstage',
    overstayAlert: '⚠️ Warnung: Überziehung der 90 Tage festgestellt!',
    maxContinuousStay: 'Maximal möglicher Aufenthalt ab diesem Datum',
    latestExit: 'Spätestes legales Ausreisedatum',
    completeReset: 'Vollständiger Reset der 90 Tage (bei Ausreise)',
    downloadIcs: '📅 Ausreise-Erinnerung in Kalender laden (.ics)',
    timelineTitle: '180-Tage rollende Zeitleiste',
    timelineSub: 'Visuelle Aufschlüsselung der Tage im 180-Tage-Fenster',
    inSchengen: 'Im Schengen-Raum',
    outSchengen: 'Außerhalb',
    faqTitle: 'Häufig gestellte Fragen (FAQ)',
    q1: 'Was ist die 90/180-Tage-Regel?',
    a1: 'Sie dürfen sich innerhalb jedes 180-Tage-Zeitraums maximal 90 Tage im gesamten Schengen-Raum aufhalten.',
    q2: 'Welche Länder gehören zum Schengen-Raum?',
    a2: '29 europäische Staaten wie Deutschland, Frankreich, Italien, Spanien, die Schweiz und Österreich. Großbritannien und Irland gehören nicht dazu.',
    q3: 'Sind meine Reisedaten sicher?',
    a3: 'Ja, 100%. Alles bleibt in Ihrem Browser und wird niemals an externe Server übertragen.'
  },
  es: {
    siteTitle: 'Calculadora Schengen 90/180',
    badge: '100% en Navegador • Cero Subida al Servidor',
    heroTitle: 'Calculadora Ventana Móvil 90/180 Días Schengen',
    heroSub: 'Calculadora precisa de ventana móvil para viajeros no comunitarios y nómadas digitales. Calcule días restantes y fechas límite de salida con privacidad absoluta.',
    privacyBadge: '🔒 Todos los viajes se guardan en su navegador (LocalStorage). Jamás se envían a un servidor.',
    addTrip: 'Añadir Viaje al Espacio Schengen',
    entryDate: 'Fecha de Entrada',
    exitDate: 'Fecha de Salida',
    country: 'País (Opcional)',
    note: 'Nota / Motivo (Opcional)',
    addBtn: '+ Añadir Viaje',
    loadSample: 'Cargar Ejemplo',
    clearAll: 'Borrar Todo',
    myTrips: 'Historial de Viajes',
    noTrips: 'No hay viajes añadidos. Ingrese fechas arriba o cargue un ejemplo.',
    duration: 'Duración',
    days: 'días',
    delete: 'Eliminar',
    simTitle: 'Estado de Estancia y Simulación',
    simSub: 'Compruebe su cumplimiento legal en cualquier fecha de referencia dentro del periodo móvil de 180 días.',
    refDateLabel: 'Fecha de Referencia',
    statusToday: 'Estado en la Fecha',
    usedDays: 'Días Consumidos (de 90)',
    remainingDays: 'Días Restantes Autorizados',
    overstayAlert: '⚠️ ¡Riesgo de estancia irregular detectado! Ha superado los 90 días.',
    maxContinuousStay: 'Estancia Continua Máxima Posible',
    latestExit: 'Fecha Límite de Salida Recomendada',
    completeReset: 'Reinicio Completo de los 90 Días (si sale)',
    downloadIcs: '📅 Descargar Recordatorio a Calendario (.ics)',
    timelineTitle: 'Línea de Tiempo Móvil de 180 Días',
    timelineSub: 'Desglose visual día a día de estancia y ausencia.',
    inSchengen: 'En Schengen',
    outSchengen: 'Fuera de Schengen',
    faqTitle: 'Preguntas Frecuentes (FAQ)',
    q1: '¿Cómo funciona la regla de los 90/180 días en el espacio Schengen?',
    a1: 'Los ciudadanos no comunitarios exentos de visado pueden permanecer un máximo de 90 días en CUALQUIER periodo móvil de 180 días.',
    q2: '¿Cuentan los días de entrada y salida?',
    a2: 'Sí, tanto el día de entrada como el de salida se computan como días completos dentro del área Schengen.',
    q3: '¿Se transmiten mis datos de viaje?',
    a3: 'Cero bytes enviados a servidores externos. Todo el cálculo se realiza localmente en su navegador.'
  },
  vi: {
    siteTitle: 'Công Cụ Tính Quy Tắc 90/180 Schengen',
    badge: '100% Trình Duyệt • 0KB Tải Lên Server',
    heroTitle: 'Tính Ngày Lưu Trú Khối Schengen (Quy Tắc 90/180)',
    heroSub: 'Công cụ tính toán chính xác khung thời gian trượt 180 ngày cho người du lịch, du học và dân du mục số (Digital Nomad). Tính ngày còn lại và ngày bắt buộc xuất cảnh không lo quá hạn visa.',
    privacyBadge: '🔒 Toàn bộ lịch trình lưu trực tiếp trong trình duyệt máy bạn (LocalStorage). Tuyệt đối không gửi lên server.',
    addTrip: 'Thêm Chuyến Đi Vào Khối Schengen',
    entryDate: 'Ngày Nhập Cảnh',
    exitDate: 'Ngày Xuất Cảnh',
    country: 'Quốc Gia (Tùy chọn)',
    note: 'Ghi chú / Mục đích (Tùy chọn)',
    addBtn: '+ Thêm Chuyến Đi',
    loadSample: 'Tải Dữ Liệu Mẫu',
    clearAll: 'Xóa Tất Cả',
    myTrips: 'Lịch Sử Các Chuyến Đi',
    noTrips: 'Chưa có chuyến đi nào. Vui lòng nhập ngày ở trên hoặc tải dữ liệu mẫu.',
    duration: 'Thời lượng',
    days: 'ngày',
    delete: 'Xóa',
    simTitle: 'Mô Phỏng & Số Ngày Được Ở Lại',
    simSub: 'Kiểm tra tính hợp pháp tại bất kỳ ngày mốc nào trong khung 180 ngày trượt liên tục.',
    refDateLabel: 'Ngày mốc để kiểm tra',
    statusToday: 'Tình trạng tại ngày mốc',
    usedDays: 'Số ngày đã dùng (trên 90)',
    remainingDays: 'Số ngày còn lại được ở',
    overstayAlert: '⚠️ Cảnh báo: Nguy cơ quá hạn visa! Bạn đã ở quá 90 ngày.',
    maxContinuousStay: 'Số ngày tối đa có thể ở liên tục từ ngày này',
    latestExit: 'Hạn chót xuất cảnh hợp pháp',
    completeReset: 'Ngày được cấp mới toàn bộ 90 ngày (nếu ở ngoài)',
    downloadIcs: '📅 Tải Lịch Nhắc Xuất Cảnh (.ics)',
    timelineTitle: 'Biểu Đồ Khung Thời Gian Trượt 180 Ngày',
    timelineSub: 'Hiển thị trực quan từng ngày bạn ở trong hay ngoài khối Schengen.',
    inSchengen: 'Trong khối Schengen',
    outSchengen: 'Ngoài khối Schengen',
    faqTitle: 'Câu Hỏi Thường Gặp (FAQ)',
    q1: 'Quy tắc 90/180 ngày của khối Schengen hoạt động như thế nào?',
    a1: 'Công dân ngoài EU được ở tối đa 90 ngày trong BẤT KỲ khoảng thời gian 180 ngày nào. Khung 180 ngày này trượt lùi liên tục từ mỗi ngày bạn có mặt.',
    q2: 'Ngày nhập cảnh và ngày xuất cảnh có tính trọn vẹn 1 ngày không?',
    a2: 'Có. Dù bạn đến lúc 23:59 hay rời đi lúc 00:01, cả ngày vào và ngày ra đều tính là 1 ngày lưu trú trọn vẹn.',
    q3: 'Dữ liệu chuyến đi của tôi có bị gửi lên mạng không?',
    a3: 'Không. Toàn bộ tính toán diễn ra ngay trên máy của bạn và chỉ lưu ở bộ nhớ máy cá nhân.'
  },
  ja: {
    siteTitle: 'シェンゲン協定 90/180日滞在計算ツール',
    badge: '100% ブラウザ内ローカル処理 • サーバー送信ゼロ',
    heroTitle: 'シェンゲン協定 90/180日ローリング滞在日数計算機',
    heroSub: 'EU圏外からの旅行者、デジタルノマド、ワーホリ向け。180日のローリングウィンドウ（移動基準期間）における残り滞在可能日数とオーバーステイ防止の出国期限を完全ローカル計算。',
    privacyBadge: '🔒 渡航データはすべてブラウザ内(LocalStorage)にのみ保存され、外部サーバーへ送信されることは一切ありません。',
    addTrip: 'シェンゲン圏への滞在履歴を追加',
    entryDate: '入国日',
    exitDate: '出国日',
    country: '滞在国 (任意)',
    note: '目的 / メモ (任意)',
    addBtn: '+ 滞在履歴を追加',
    loadSample: 'サンプルデータを読み込む',
    clearAll: 'すべて削除',
    myTrips: '登録済み滞在履歴一覧',
    noTrips: '登録された滞在履歴がありません。上のフォームから入力するかサンプルを読み込んでください。',
    duration: '滞在期間',
    days: '日間',
    delete: '削除',
    simTitle: '滞在状況シミュレーション＆残り日数',
    simSub: '指定した基準日から過去180日間の移動枠を基準に、合法滞在状況をリアルタイム診断します。',
    refDateLabel: '計算の基準日',
    statusToday: '基準日時点でのステータス',
    usedDays: '使用済み日数 (上限90日中)',
    remainingDays: '滞在可能残り日数',
    overstayAlert: '⚠️ 警告: 90日超過のオーバーステイ（不法滞在）リスクが検出されました！',
    maxContinuousStay: 'この基準日から連続滞在可能な最大日数',
    latestExit: '合法的に滞在できる最終出国期限日',
    completeReset: '90日の全日数がリセットされる日 (出国維持の場合)',
    downloadIcs: '📅 出国リマインダーをカレンダーに追加 (.ics)',
    timelineTitle: '180日間ローリングタイムライン可視化',
    timelineSub: '180日間の枠内でのシェンゲン滞在日と圏外滞在日の日別グラフィカル表示。',
    inSchengen: 'シェンゲン圏内',
    outSchengen: 'シェンゲン圏外',
    faqTitle: 'よくある質問 (FAQ)',
    q1: 'シェンゲン協定の「90/180日ルール」とは何ですか？',
    a1: 'ビザ免除の非EU市民は、「あらゆる180日間の期間内において、最大90日まで」シェンゲン圏に滞在できます。初回入国日からではなく、滞在中のどの日から振り返っても過去180日間に90日を超えてはならない「ローリング（移動枠）」方式です。',
    q2: '入国日と出国日もそれぞれ1日としてカウントされますか？',
    a2: 'はい。夜23時59分に入国した場合や深夜0時1分に出国した場合でも、出入国日はそれぞれ丸1日の滞在として合算されます。',
    q3: 'パスポート番号や旅行日程が外部に流出する心配はありませんか？',
    a3: '一切ありません。すべての計算はお使いの端末のブラウザ内でJavaScriptによって完結し、外部サーバーに通信することは0バイトです。'
  },
  ko: {
    siteTitle: '솅겐 90/180 체류일수 계산기',
    badge: '100% 클라이언트 연산 • 서버 전송 0KB',
    heroTitle: '솅겐 90/180일 롤링 윈도우 체류일수 정밀 계산기',
    heroSub: '유럽 솅겐 협약국 무비자 90일 체류 규정을 정확하게 계산합니다. 180일 롤링 윈도우 기반 실시간 시뮬레이션, 출국 마감일 자동 계산, 오버스테이 방지 알림을 서버 전송 없이 100% 안전하게 제공합니다.',
    privacyBadge: '🔒 모든 여행 기록은 사용자 브라우저(LocalStorage)에만 안전하게 보관되며 외부 서버로 전송되지 않습니다.',
    addTrip: '새 유럽 솅겐 입출국 일정 추가',
    entryDate: '입국일 (Entry)',
    exitDate: '출국일 (Exit)',
    country: '방문국 (선택)',
    note: '메모 / 목적 (선택)',
    addBtn: '+ 일정 등록',
    loadSample: '샘플 일정 불러오기',
    clearAll: '모두 초기화',
    myTrips: '등록된 솅겐 여행 기록',
    noTrips: '등록된 일정이 없습니다. 위 입력창에서 입출국 날짜를 등록하거나 샘플 일정을 불러오세요.',
    duration: '체류 기간',
    days: '일간',
    delete: '삭제',
    simTitle: '체류 상태 시뮬레이션 & 잔여 일수',
    simSub: '기준일(오늘 또는 예정일)을 변경하여 180일 롤링 윈도우 기준 합법 체류 가능 여부를 검증하세요.',
    refDateLabel: '시뮬레이션 기준일',
    statusToday: '기준일 기준 체류 상태',
    usedDays: '사용한 일수 (최대 90일 중)',
    remainingDays: '남은 체류 가능 일수',
    overstayAlert: '⚠️ 경고: 90일 체류 한도를 초과하여 오버스테이(불법체류) 위험이 있습니다!',
    maxContinuousStay: '기준일로부터 연속 체류 가능한 최대 일수',
    latestExit: '가장 늦게 출국해야 하는 합법 출국일',
    completeReset: '90일 체류 권한이 완전히 리셋(초기화)되는 날',
    downloadIcs: '📅 캘린더 등록용 출국 마감 일정 다운로드 (.ics)',
    timelineTitle: '180일 롤링 타임라인 시각화',
    timelineSub: '기준일로부터 과거 180일 동안의 솅겐 체류일과 비체류일을 일별로 확인하세요.',
    inSchengen: '솅겐 체류',
    outSchengen: '솅겐 외 체류',
    faqTitle: '자주 묻는 질문 (FAQ)',
    q1: '솅겐 90/180일 규정이란 무엇인가요?',
    a1: '비유럽권 무비자 여행자는 어떤 180일의 기간을 잡아도 솅겐 협약국 내에 최대 90일까지만 체류할 수 있습니다. 최초 입국일 기준이 아니라, 체류하는 모든 날을 기준으로 과거 180일을 항상 뒤돌아보는 \'롤링 윈도우(Rolling Window)\' 방식입니다.',
    q2: '입국일과 출국일도 체류 일수에 포함되나요?',
    a2: '네, 포함됩니다. 밤 23시 59분에 입국하거나 새벽 0시 1분에 출국하더라도 입국일과 출국일은 각각 온전한 1일 체류로 계산됩니다.',
    q3: '제 여행 일정이나 여권 정보가 서버에 저장되나요?',
    a3: '아닙니다. 모든 계산 알고리즘은 사용자의 웹 브라우저 메모리에서 100% 로컬로 실행되며, 입력한 일정 데이터는 브라우저 내부 로컬스토리지에만 저장됩니다.'
  }
};
