import { writable } from 'svelte/store';

export type Lang = 'ja' | 'ko' | 'en';

export const currentLang = writable<Lang>('ja');

export const translations = {
  ja: {
    siteTitle: '履歴書作成ツール',
    subBrand: 'JIS規格 A4 PDF印刷 & 和暦自動計算',
    badge: '🔒 サーバー送信0KB・完全ローカル',
    tabBasic: '基本情報',
    tabEdu: '学歴・職歴',
    tabBio: '志望動機・特技',
    tabEdit: '入力・編集',
    recalculateBtn: '⚡ 学歴和暦を再計算',
    noWorkNotice: '職歴なしの場合は「なし」と自動記載されます。職歴がある場合は行を追加してください。',
    preview: '印刷プレビュー',
    printBtn: 'A4で印刷 / PDF保存',
    resetBtn: 'リセット',
    name: '氏名',
    nameFurigana: 'ふりがな',
    birthDate: '生年月日',
    gender: '性別',
    genderMale: '男',
    genderFemale: '女',
    genderNone: '未記入',
    phone: '電話番号',
    email: 'メールアドレス',
    address: '現住所',
    addressFurigana: 'ふりがな (住所)',
    postalCode: '郵便番号',
    photo: '証明写真 (40x30mm)',
    photoUpload: '写真をアップロード',
    photoRemove: '写真を削除',
    year: '年',
    month: '月',
    day: '日',
    autoCalcNotice: '生年月日を入力すると、小学校から大学までの入学・卒業年度（西暦/和暦）が自動入力されます。',
    educationHeader: '学歴',
    workHeader: '職歴',
    licensesHeader: '免許・資格',
    motivationHeader: '志望の動機・特技・アピールポイント',
    requestsHeader: '本人希望記入欄（給与・職種・勤務時間等）',
    addRow: '+ 行を追加',
    removeRow: '削除',
    endMark: '以上',
    footerSecurity: '入力されたすべての個人情報はブラウザ内（ローカルストレージ）のみに保持され、外部サーバーにアップロードされることは一切ありません。',
    faqTitle: 'よくある質問',
    faq1Q: 'Q. 和暦（令和・平成・昭和）の計算は正しいですか？',
    faq1A: 'A. はい。4月2日〜翌年4月1日の日本の学校年度（早生まれ判定含む）に基づき、小学校・中学校・高校・大学の入学・卒業年を自動算出します。',
    faq2Q: 'Q. JIS規格の履歴書とは何ですか？',
    faq2A: 'A. 日本産業規格（JIS）に基づいた最も標準的かつ公認性の高いフォーマットです。A4サイズ1〜2枚にきれいに収まるよう最適化されています。'
  },
  ko: {
    siteTitle: '일본 이력서 와레키 자동완성',
    subBrand: 'JIS 규격 A4 PDF 출력 & 일본 연호 계산기',
    badge: '🔒 서버 전송 0KB 완전 로컬',
    tabBasic: '기본 정보',
    tabEdu: '학력·경력',
    tabBio: '지원동기·자기PR',
    tabEdit: '입력 편집',
    recalculateBtn: '⚡ 학력 와레키 재계산',
    noWorkNotice: '경력이 없는 경우 "なし(없음)"으로 자동 표기됩니다. 경력이 있으면 행을 추가하세요.',
    preview: '인쇄 미리보기',
    printBtn: 'A4 인쇄 / PDF 저장',
    resetBtn: '초기화',
    name: '성명 (한자/영문)',
    nameFurigana: '후리가나 (히라가나)',
    birthDate: '생년월일',
    gender: '성별',
    genderMale: '남',
    genderFemale: '여',
    genderNone: '미기재',
    phone: '전화번호',
    email: '이메일',
    address: '현주소',
    addressFurigana: '주소 후리가나',
    postalCode: '우편번호',
    photo: '증명사진 (40x30mm)',
    photoUpload: '사진 첨부',
    photoRemove: '사진 삭제',
    year: '년',
    month: '월',
    day: '일',
    autoCalcNotice: '생년월일을 입력하면 일본식 4월 학기제(조기입학/빠른년생 포함)에 맞춰 초등학교부터 대학교 입학/졸업 년도(와레키 및 서력)가 자동 생성됩니다.',
    educationHeader: '학력 (学歴)',
    workHeader: '경력 (職歴)',
    licensesHeader: '면허·자격증 (免許・資格)',
    motivationHeader: '지원동기·자기PR (志望動機)',
    requestsHeader: '희망 근무조건 (本人希望記入欄)',
    addRow: '+ 행 추가',
    removeRow: '삭제',
    endMark: '이상 (以上)',
    footerSecurity: '작성하신 모든 정보와 사진은 브라우저 메모리에만 보관되며, 서버로 1바이트도 전송되지 않아 안심하고 작성하실 수 있습니다.',
    faqTitle: '자주 묻는 질문 (FAQ)',
    faq1Q: 'Q. 일본의 와레키(令和・平成・昭和)와 학력 계산은 정확한가요?',
    faq1A: 'A. 네, 일본의 공식 회계/학사 연도 기준(4월 2일 ~ 익년 4월 1일) 및 3월 졸업/4월 입학 주기를 정확히 반영하여 와레키(Reiwa/Heisei/Showa)로 자동 계산합니다.',
    faq2Q: 'Q. 출력 시 규격은 어떻게 되나요?',
    faq2A: 'A. 일본 취업/비자 신청 시 가장 표준으로 통용되는 JIS 규격 A4(좌우/앞뒤 2페이지) 맞춤 레이아웃으로, 브라우저 인쇄(Ctrl+P / Cmd+P) 시 여백 없이 완벽하게 인쇄되거나 PDF로 저장됩니다.'
  },
  en: {
    siteTitle: 'Japan Resume Builder',
    subBrand: 'JIS Standard A4 PDF & Wareki Era Converter',
    badge: '🔒 0KB Server Uploads · 100% In-Browser',
    tabBasic: 'Basic Info',
    tabEdu: 'Education & Career',
    tabBio: 'Motivation & PR',
    tabEdit: 'Edit Form',
    recalculateBtn: '⚡ Recalculate Education Eras',
    noWorkNotice: 'If no work history, it will be marked as "なし". Add rows if you have experience.',
    preview: 'Print Preview',
    printBtn: 'Print A4 / Save PDF',
    resetBtn: 'Reset Form',
    name: 'Full Name',
    nameFurigana: 'Furigana (Hiragana)',
    birthDate: 'Date of Birth',
    gender: 'Gender',
    genderMale: 'Male',
    genderFemale: 'Female',
    genderNone: 'Do not specify',
    phone: 'Phone Number',
    email: 'Email Address',
    address: 'Address in Japan',
    addressFurigana: 'Address Furigana',
    postalCode: 'Postal Code',
    photo: 'ID Photo (40x30mm)',
    photoUpload: 'Upload Photo',
    photoRemove: 'Remove Photo',
    year: 'Year',
    month: 'Month',
    day: 'Day',
    autoCalcNotice: 'Entering your date of birth automatically calculates Japanese school admission & graduation years in both Western and Wareki (Reiwa, Heisei, Showa) format.',
    educationHeader: 'Education (学歴)',
    workHeader: 'Work Experience (職歴)',
    licensesHeader: 'Licenses & Certificates (免許・資格)',
    motivationHeader: 'Motivation & Self PR (志望動機)',
    requestsHeader: 'Personal Requests (本人希望記入欄)',
    addRow: '+ Add Row',
    removeRow: 'Delete',
    endMark: 'End (以上)',
    footerSecurity: 'All information is processed strictly within your local browser. Zero server uploads guarantee your privacy.',
    faqTitle: 'Frequently Asked Questions',
    faq1Q: 'Q. How are the Japanese Wareki eras and school timelines calculated?',
    faq1A: 'A. Japan follows an April to March academic year. The tool precisely calculates school admission and graduation dates based on your birthday and converts them to Wareki eras.',
    faq2Q: 'Q. Can I use this for Japanese visa or job applications?',
    faq2A: 'A. Yes. It formats strictly to JIS standards in crisp A4 dimensions ready to print or save as PDF.'
  }
};
