import { writable } from 'svelte/store';

export type Lang = 'en' | 'fr' | 'de' | 'es' | 'vi' | 'ja' | 'ko';

export const currentLang = writable<Lang>('ja');

export const translations: Record<Lang, {
  siteTitle: string;
  subBrand: string;
  badge: string;
  tabBasic: string;
  tabEdu: string;
  tabBio: string;
  tabEdit: string;
  recalculateBtn: string;
  noWorkNotice: string;
  preview: string;
  printBtn: string;
  resetBtn: string;
  name: string;
  nameFurigana: string;
  birthDate: string;
  gender: string;
  genderMale: string;
  genderFemale: string;
  genderNone: string;
  phone: string;
  email: string;
  address: string;
  addressFurigana: string;
  postalCode: string;
  photo: string;
  photoUpload: string;
  photoRemove: string;
  year: string;
  month: string;
  day: string;
  autoCalcNotice: string;
  educationHeader: string;
  workHeader: string;
  licensesHeader: string;
  motivationHeader: string;
  requestsHeader: string;
  addRow: string;
  removeRow: string;
  endMark: string;
  footerSecurity: string;
  faqTitle: string;
  faq1Q: string;
  faq1A: string;
  faq2Q: string;
  faq2A: string;
}> = {
  ja: {
    siteTitle: '履歴書作成ツール',
    subBrand: 'JIS規格 A4 PDF印刷 & 和暦自動計算',
    badge: '🔒 サーバー送信0KB・完全ローカル',
    tabBasic: '基本情報',
    tabEdu: '学歴・職歴',
    tabBio: '志望動機・特技',
    tabEdit: '入力・編集',
    recalculateBtn: '⚡ 学歴和暦を再計算',
    noWorkNotice: '職歴なしの場合は「なし」と自動記載されます。職歴がある場合は行を追加してください。',
    preview: '印刷プレビュー',
    printBtn: 'A4で印刷 / PDF保存',
    resetBtn: 'リセット',
    name: '氏名',
    nameFurigana: 'ふりがな',
    birthDate: '生年月日',
    gender: '性別',
    genderMale: '男',
    genderFemale: '女',
    genderNone: '未記入',
    phone: '電話番号',
    email: 'メールアドレス',
    address: '現住所',
    addressFurigana: 'ふりがな (住所)',
    postalCode: '郵便番号',
    photo: '証明写真 (40x30mm)',
    photoUpload: '写真をアップロード',
    photoRemove: '写真を削除',
    year: '年',
    month: '月',
    day: '日',
    autoCalcNotice: '生年月日を入力すると、小学校から大学までの入学・卒業年度（西暦/和暦）が自動入力されます。',
    educationHeader: '学歴',
    workHeader: '職歴',
    licensesHeader: '免許・資格',
    motivationHeader: '志望の動機・特技・アピールポイント',
    requestsHeader: '本人希望記入欄（給与・職種・勤務時間等）',
    addRow: '+ 行を追加',
    removeRow: '削除',
    endMark: '以上',
    footerSecurity: '入力されたすべての個人情報はブラウザ内（ローカルストレージ）のみに保持され、外部サーバーにアップロードされることは一切ありません。',
    faqTitle: 'よくある質問',
    faq1Q: 'Q. 和暦（令和・平成・昭和）の計算は正しいですか？',
    faq1A: 'A. はい。4月2日〜翌年4月1日の日本の学校年度（早生まれ判定含む）に基づき、小学校・中学校・高校・大学の入学・卒業年を自動算出します。',
    faq2Q: 'Q. JIS規格の履歴書とは何ですか？',
    faq2A: 'A. 日本産業規格（JIS）に基づいた最も標準的かつ公認性の高いフォーマットです。A4サイズ1〜2枚にきれいに収まるよう最適化されています。'
  },
  ko: {
    siteTitle: '일본 이력서 와레키 자동완성',
    subBrand: 'JIS 규격 A4 PDF 출력 & 일본 연호 계산기',
    badge: '🔒 서버 전송 0KB 완전 로컬',
    tabBasic: '기본 정보',
    tabEdu: '학력·경력',
    tabBio: '지원동기·자기PR',
    tabEdit: '입력 편집',
    recalculateBtn: '⚡ 학력 와레키 재계산',
    noWorkNotice: '경력이 없는 경우 "なし(없음)"으로 자동 표기됩니다. 경력이 있으면 행을 추가하세요.',
    preview: '인쇄 미리보기',
    printBtn: 'A4 인쇄 / PDF 저장',
    resetBtn: '초기화',
    name: '성명 (한자/영문)',
    nameFurigana: '후리가나 (히라가나)',
    birthDate: '생년월일',
    gender: '성별',
    genderMale: '남',
    genderFemale: '여',
    genderNone: '미기재',
    phone: '전화번호',
    email: '이메일',
    address: '현주소',
    addressFurigana: '주소 후리가나',
    postalCode: '우편번호',
    photo: '증명사진 (40x30mm)',
    photoUpload: '사진 첨부',
    photoRemove: '사진 삭제',
    year: '년',
    month: '월',
    day: '일',
    autoCalcNotice: '생년월일을 입력하면 일본식 4월 학기제(조기입학/빠른년생 포함)에 맞춰 초등학교부터 대학교 입학/졸업 년도(와레키 및 서력)가 자동 생성됩니다.',
    educationHeader: '학력 (学歴)',
    workHeader: '경력 (職歴)',
    licensesHeader: '면허·자격증 (免許・資格)',
    motivationHeader: '지원동기·자기PR (志望動機)',
    requestsHeader: '희망 근무조건 (本人希望記入欄)',
    addRow: '+ 행 추가',
    removeRow: '삭제',
    endMark: '이상 (以上)',
    footerSecurity: '작성하신 모든 정보와 사진은 브라우저 메모리에만 보관되며, 서버로 1바이트도 전송되지 않아 안심하고 작성하실 수 있습니다.',
    faqTitle: '자주 묻는 질문 (FAQ)',
    faq1Q: 'Q. 일본의 와레키(令和・平成・昭和)와 학력 계산은 정확한가요?',
    faq1A: 'A. 네, 일본의 공식 회계/학사 연도 기준(4월 2일 ~ 익년 4월 1일) 및 3월 졸업/4월 입학 주기를 정확히 반영하여 와레키(Reiwa/Heisei/Showa)로 자동 계산합니다.',
    faq2Q: 'Q. 출력 시 규격은 어떻게 되나요?',
    faq2A: 'A. 일본 취업/비자 신청 시 가장 표준으로 통용되는 JIS 규격 A4(좌우/앞뒤 2페이지) 맞춤 레이아웃으로, 브라우저 인쇄(Ctrl+P / Cmd+P) 시 여백 없이 완벽하게 인쇄되거나 PDF로 저장됩니다.'
  },
  en: {
    siteTitle: 'Japan Resume Builder',
    subBrand: 'JIS Standard A4 PDF & Wareki Era Converter',
    badge: '🔒 0KB Server Uploads · 100% In-Browser',
    tabBasic: 'Basic Info',
    tabEdu: 'Education & Career',
    tabBio: 'Motivation & PR',
    tabEdit: 'Edit Form',
    recalculateBtn: '⚡ Recalculate Education Eras',
    noWorkNotice: 'If no work history, it will be marked as "なし". Add rows if you have experience.',
    preview: 'Print Preview',
    printBtn: 'Print A4 / Save PDF',
    resetBtn: 'Reset Form',
    name: 'Full Name',
    nameFurigana: 'Furigana (Hiragana)',
    birthDate: 'Date of Birth',
    gender: 'Gender',
    genderMale: 'Male',
    genderFemale: 'Female',
    genderNone: 'Do not specify',
    phone: 'Phone Number',
    email: 'Email Address',
    address: 'Address in Japan',
    addressFurigana: 'Address Furigana',
    postalCode: 'Postal Code',
    photo: 'ID Photo (40x30mm)',
    photoUpload: 'Upload Photo',
    photoRemove: 'Remove Photo',
    year: 'Year',
    month: 'Month',
    day: 'Day',
    autoCalcNotice: 'Entering your date of birth automatically calculates Japanese school admission & graduation years in both Western and Wareki (Reiwa, Heisei, Showa) format.',
    educationHeader: 'Education (学歴)',
    workHeader: 'Work Experience (職歴)',
    licensesHeader: 'Licenses & Certificates (免許・資格)',
    motivationHeader: 'Motivation & Self PR (志望動機)',
    requestsHeader: 'Personal Requests (本人希望記入欄)',
    addRow: '+ Add Row',
    removeRow: 'Delete',
    endMark: 'End (以上)',
    footerSecurity: 'All information is processed strictly within your local browser. Zero server uploads guarantee your privacy.',
    faqTitle: 'Frequently Asked Questions',
    faq1Q: 'Q. How are the Japanese Wareki eras and school timelines calculated?',
    faq1A: 'A. Japan follows an April to March academic year. The tool precisely calculates school admission and graduation dates based on your birthday and converts them to Wareki eras.',
    faq2Q: 'Q. Can I use this for Japanese visa or job applications?',
    faq2A: 'A. Yes. It formats strictly to JIS standards in crisp A4 dimensions ready to print or save as PDF.'
  },
  fr: {
    siteTitle: 'Créateur de CV Japonais (Rirekisho)',
    subBrand: 'Norme JIS A4 PDF & Conversion d\'ères Wareki',
    badge: '🔒 0 Ko Serveur · 100% Navigateur',
    tabBasic: 'Infos de base',
    tabEdu: 'Formation & Carrière',
    tabBio: 'Motivation & Atouts',
    tabEdit: 'Éditer',
    recalculateBtn: '⚡ Recalculer les ères scolaires',
    noWorkNotice: 'Sans expérience, la mention "なし" s\'affiche. Ajoutez des lignes si besoin.',
    preview: 'Aperçu avant impression',
    printBtn: 'Imprimer A4 / Enregistrer PDF',
    resetBtn: 'Réinitialiser',
    name: 'Nom complet',
    nameFurigana: 'Furigana (Hiragana)',
    birthDate: 'Date de naissance',
    gender: 'Genre',
    genderMale: 'Homme',
    genderFemale: 'Femme',
    genderNone: 'Non précisé',
    phone: 'Téléphone',
    email: 'E-mail',
    address: 'Adresse au Japon',
    addressFurigana: 'Furigana de l\'adresse',
    postalCode: 'Code postal',
    photo: 'Photo d\'identité (40x30mm)',
    photoUpload: 'Téléverser photo',
    photoRemove: 'Supprimer',
    year: 'Année',
    month: 'Mois',
    day: 'Jour',
    autoCalcNotice: 'Votre date de naissance calcule automatiquement les années d\'entrée et de diplôme (occidental et ères Wareki Reiwa/Heisei/Showa).',
    educationHeader: 'Formation (学歴)',
    workHeader: 'Expérience pro (職歴)',
    licensesHeader: 'Permis & Certificats (免許・資格)',
    motivationHeader: 'Motivation & Points forts (志望動機)',
    requestsHeader: 'Souhaits particuliers (本人希望記入欄)',
    addRow: '+ Ajouter ligne',
    removeRow: 'Supprimer',
    endMark: 'Fin (以上)',
    footerSecurity: 'Toutes les données restent dans votre navigateur. Aucun envoi sur un serveur distant.',
    faqTitle: 'Foire Aux Questions (FAQ)',
    faq1Q: 'Q. Comment sont calculées les ères japonaises Wareki et le calendrier scolaire ?',
    faq1A: 'A. Le Japon applique l\'année scolaire d\'avril à mars. L\'outil calcule précisément chaque étape selon la norme JIS.',
    faq2Q: 'Q. Ce modèle convient-il pour un visa ou un emploi au Japon ?',
    faq2A: 'A. Oui, c\'est le format standard officiel JIS imprimable en A4.'
  },
  de: {
    siteTitle: 'Japanischer Lebenslauf-Generator (Rirekisho)',
    subBrand: 'JIS-Standard A4 PDF & Wareki-Ärenumrechner',
    badge: '🔒 0 KB Server-Uploads · 100% Im Browser',
    tabBasic: 'Basisdaten',
    tabEdu: 'Bildung & Beruf',
    tabBio: 'Motivation & Stärken',
    tabEdit: 'Bearbeiten',
    recalculateBtn: '⚡ Schul- und Ärendaten neu berechnen',
    noWorkNotice: 'Ohne Berufserfahrung wird "なし" eingetragen. Fügen Sie Zeilen hinzu, falls vorhanden.',
    preview: 'Druckvorschau',
    printBtn: 'A4 drucken / Als PDF speichern',
    resetBtn: 'Zurücksetzen',
    name: 'Vollständiger Name',
    nameFurigana: 'Furigana (Hiragana)',
    birthDate: 'Geburtsdatum',
    gender: 'Geschlecht',
    genderMale: 'Männlich',
    genderFemale: 'Weiblich',
    genderNone: 'Keine Angabe',
    phone: 'Telefon',
    email: 'E-Mail',
    address: 'Wohnadresse in Japan',
    addressFurigana: 'Adresse Furigana',
    postalCode: 'Postleitzahl',
    photo: 'Passbild (40x30mm)',
    photoUpload: 'Foto hochladen',
    photoRemove: 'Foto entfernen',
    year: 'Jahr',
    month: 'Monat',
    day: 'Tag',
    autoCalcNotice: 'Die Eingabe des Geburtsdatums berechnet japanische Schuljahre in westlicher Zeitrechnung und Wareki (Reiwa, Heisei, Showa) automatisch.',
    educationHeader: 'Bildungsweg (学歴)',
    workHeader: 'Berufserfahrung (職歴)',
    licensesHeader: 'Lizenzen & Zertifikate (免許・資格)',
    motivationHeader: 'Motivation & Selbstpräsentation (志望動機)',
    requestsHeader: 'Persönliche Wünsche (本人希望記入欄)',
    addRow: '+ Zeile hinzufügen',
    removeRow: 'Löschen',
    endMark: 'Ende (以上)',
    footerSecurity: 'Alle Daten verbleiben lokal in Ihrem Browser. Keine Server-Übertragung garantiert höchste Privatsphäre.',
    faqTitle: 'Häufig gestellte Fragen (FAQ)',
    faq1Q: 'Q. Entspricht die Formatierung den Vorgaben in Japan?',
    faq1A: 'A. Ja, sie folgt exakt dem japanischen JIS-Standard für A4-Lebensläufe.',
    faq2Q: 'Q. Kann ich den Lebenslauf für Visa und Bewerbungen nutzen?',
    faq2A: 'A. Ja, dies ist das offizielle Standardformat in ganz Japan.'
  },
  es: {
    siteTitle: 'Generador de Currículum Japonés (Rirekisho)',
    subBrand: 'Norma JIS Estándar A4 PDF & Conversor de Eras Wareki',
    badge: '🔒 0KB Servidor · 100% En Navegador',
    tabBasic: 'Datos Básicos',
    tabEdu: 'Educación y Empleo',
    tabBio: 'Motivación y PR',
    tabEdit: 'Editar',
    recalculateBtn: '⚡ Recalcular eras académicas',
    noWorkNotice: 'Sin experiencia previa se marca "なし". Agrega filas si tienes experiencia.',
    preview: 'Vista previa de impresión',
    printBtn: 'Imprimir A4 / Guardar PDF',
    resetBtn: 'Restablecer',
    name: 'Nombre completo',
    nameFurigana: 'Furigana (Hiragana)',
    birthDate: 'Fecha de nacimiento',
    gender: 'Género',
    genderMale: 'Hombre',
    genderFemale: 'Mujer',
    genderNone: 'No especificar',
    phone: 'Teléfono',
    email: 'Correo electrónico',
    address: 'Dirección en Japón',
    addressFurigana: 'Furigana de la dirección',
    postalCode: 'Código postal',
    photo: 'Foto carnet (40x30mm)',
    photoUpload: 'Subir foto',
    photoRemove: 'Eliminar',
    year: 'Año',
    month: 'Mes',
    day: 'Día',
    autoCalcNotice: 'Al ingresar la fecha de nacimiento se calculan automáticamente los años escolares en formato occidental y eras Wareki (Reiwa, Heisei, Showa).',
    educationHeader: 'Educación (学歴)',
    workHeader: 'Experiencia laboral (職歴)',
    licensesHeader: 'Licencias y Certificaciones (免許・資格)',
    motivationHeader: 'Motivación y Presentación (志望動機)',
    requestsHeader: 'Peticiones personales (本人希望記入欄)',
    addRow: '+ Agregar fila',
    removeRow: 'Eliminar',
    endMark: 'Fin (以上)',
    footerSecurity: 'Toda la información se procesa localmente en tu navegador sin subidas a servidores externos.',
    faqTitle: 'Preguntas frecuentes (FAQ)',
    faq1Q: 'Q. ¿Este formato es válido para visas y empleos en Japón?',
    faq1A: 'A. Sí, cumple estrictamente con el estándar industrial japonés (JIS) en formato A4.',
    faq2Q: 'Q. ¿Cómo calcula las eras Wareki?',
    faq2A: 'A. Sigue el ciclo escolar japonés de abril a marzo y convierte los años a Reiwa, Heisei o Showa de forma exacta.'
  },
  vi: {
    siteTitle: 'Công cụ tạo CV tiếng Nhật (Rirekisho)',
    subBrand: 'Chuẩn JIS A4 PDF & Tự động tính niên hiệu Wareki',
    badge: '🔒 0KB Máy chủ · 100% Trên Trình Duyệt',
    tabBasic: 'Thông tin cá nhân',
    tabEdu: 'Học vấn & Kinh nghiệm',
    tabBio: 'Lý do ứng tuyển & PR',
    tabEdit: 'Chỉnh sửa',
    recalculateBtn: '⚡ Tính lại niên hiệu học vấn',
    noWorkNotice: 'Nếu chưa có kinh nghiệm, hệ thống tự điền "なし". Hãy thêm dòng nếu có kinh nghiệm làm việc.',
    preview: 'Xem trước bản in',
    printBtn: 'In khổ A4 / Lưu PDF',
    resetBtn: 'Làm lại',
    name: 'Họ và tên',
    nameFurigana: 'Furigana (Hiragana)',
    birthDate: 'Ngày tháng năm sinh',
    gender: 'Giới tính',
    genderMale: 'Nam',
    genderFemale: 'Nữ',
    genderNone: 'Không ghi',
    phone: 'Số điện thoại',
    email: 'Email',
    address: 'Địa chỉ tại Nhật Bản',
    addressFurigana: 'Furigana địa chỉ',
    postalCode: 'Mã bưu điện',
    photo: 'Ảnh thẻ (40x30mm)',
    photoUpload: 'Tải ảnh lên',
    photoRemove: 'Xóa ảnh',
    year: 'Năm',
    month: 'Tháng',
    day: 'Ngày',
    autoCalcNotice: 'Nhập ngày sinh sẽ tự động tính năm nhập học và tốt nghiệp từ tiểu học đến đại học theo lịch Tây và niên hiệu Wareki (Reiwa, Heisei, Showa).',
    educationHeader: 'Học vấn (学歴)',
    workHeader: 'Lịch sử làm việc (職歴)',
    licensesHeader: 'Bằng cấp & Chứng chỉ (免許・資格)',
    motivationHeader: 'Lý do ứng tuyển & Điểm mạnh (志望動機)',
    requestsHeader: 'Nguyện vọng cá nhân (本人希望記入欄)',
    addRow: '+ Thêm dòng',
    removeRow: 'Xóa',
    endMark: 'Hết (以上)',
    footerSecurity: 'Mọi dữ liệu cá nhân chỉ lưu trong trình duyệt của bạn, tuyệt đối không gửi lên máy chủ bên ngoài.',
    faqTitle: 'Câu hỏi thường gặp (FAQ)',
    faq1Q: 'Q. Mẫu này có chuẩn để nộp xin việc và visa Nhật Bản không?',
    faq1A: 'A. Có, mẫu tuân thủ nghiêm ngặt theo tiêu chuẩn công nghiệp Nhật Bản (JIS) khổ giấy A4.',
    faq2Q: 'Q. Niên hiệu Wareki được tính như thế nào?',
    faq2A: 'A. Tính toán tự động theo năm học tháng 4 tại Nhật, chính xác tuyệt đối các thời kỳ Reiwa, Heisei và Showa.'
  }
};
